tbSTONE_GDP = {nG = 6, nD = 1, nP = 30104}
nTSK_DAILY_REFINE_LIMIT = 2727
nDAILY_REFINE_MAX_COUNT = 5
tbRE_Formula = 
	{
		[1828] = {strName = "Tö M·ng V« T­íng Hé UyÓn", nStoneRequire =  1},
		[1838] = {strName = "Tö M·ng Tø Kh«ng Hé UyÓn", nStoneRequire =  1},
		[1848] = {strName = "Tö M·ng Thanh TÞnh Hé UyÓn", nStoneRequire =  1},
		[1858] = {strName = "Tö M·ng Sïng Minh Thóc UyÓn", nStoneRequire =  1},
		[1868] = {strName = "Tö M·ng §Þnh H¶i Thóc UyÓn", nStoneRequire =  1},
		[1878] = {strName = "Tö M·ng Tuyªn Uy Thóc UyÓn", nStoneRequire =  1},
		[1888] = {strName = "Tö M·ng XuÊt ThÇn Hé UyÓn", nStoneRequire =  1},
		[1898] = {strName = "Tö M·ng Méc TuyÕt Hé UyÓn", nStoneRequire =  1},
		[1908] = {strName = "Tö M·ng Thanh S­¬ng Tô", nStoneRequire =  1},
		[1918] = {strName = "Tö M·ng ThÕ H­¬ng Tô", nStoneRequire =  1},
		[1928] = {strName = "Tö M·ng Thùc Cèt Hé UyÓn", nStoneRequire =  1},
		[1938] = {strName = "Tö M·ng Xuyªn T©m Hé UyÓn", nStoneRequire =  1},
		[1948] = {strName = "Tö M·ng Lang Nha Hé UyÓn", nStoneRequire =  1},
		[1958] = {strName = "Tö M·ng Thanh Vô Hé UyÓn", nStoneRequire =  1},
		[1968] = {strName = "Tö M·ng Phong S­¬ng Hé UyÓn", nStoneRequire =  1},
		[1978] = {strName = "Tö M·ng MËt V©n Hé UyÓn", nStoneRequire =  1},
		[1988] = {strName = "Tö M·ng Háa V©n Hé UyÓn", nStoneRequire =  1},
		[1998] = {strName = "Tö M·ng Dung Kim Hé UyÓn", nStoneRequire =  1},
		[2008] = {strName = "Tö M·ng Liªu Nguyªn Hé UyÓn", nStoneRequire =  1},
		[2018] = {strName = "Tö M·ng Ch©n Nguyªn Tô", nStoneRequire =  1},
		[2028] = {strName = "Tö M·ng Ch©n Vò Tô", nStoneRequire =  1},
		[2038] = {strName = "Tö M·ng §o¹n Thñy Hé UyÓn", nStoneRequire =  1},
		[2048] = {strName = "Tö M·ng TrÝch Tinh Thñ", nStoneRequire =  1},
		[1826] = {strName = "Tö M·ng V« T­íng T¨ng M·o", nStoneRequire =  1},
		[1836] = {strName = "Tö M·ng Tø Kh«ng T¨ng M·o", nStoneRequire =  1},
		[1846] = {strName = "Tö M·ng Thanh TÞnh T¨ng M·o", nStoneRequire =  1},
		[1856] = {strName = "Tö M·ng Sïng Minh Kh«i", nStoneRequire =  1},
		[1866] = {strName = "Tö M·ng §Þnh H¶i Kh«i", nStoneRequire =  1},
		[1876] = {strName = "Tö M·ng Tuyªn Uy Kh«i", nStoneRequire =  1},
		[1886] = {strName = "Tö M·ng XuÊt ThÇn Ph¸t §¸i", nStoneRequire =  1},
		[1896] = {strName = "Tö M·ng Méc TuyÕt Ph¸t §¸i", nStoneRequire =  1},
		[1906] = {strName = "Tö M·ng Thanh S­¬ng Tr©m", nStoneRequire =  1},
		[1916] = {strName = "Tö M·ng ThÕ H­¬ng Tr©m", nStoneRequire =  1},
		[1926] = {strName = "Tö M·ng Thùc Cèt Ph¸t §¸i", nStoneRequire =  1},
		[1936] = {strName = "Tö M·ng Xuyªn T©m Ph¸t §¸i", nStoneRequire =  1},
		[1946] = {strName = "Tö M·ng Lang Nha Qu¸n", nStoneRequire =  1},
		[1956] = {strName = "Tö M·ng Thanh Vô Qu¸n", nStoneRequire =  1},
		[1966] = {strName = "Tö M·ng Phong S­¬ng Ph¸t Qu¸n", nStoneRequire =  1},
		[1976] = {strName = "Tö M·ng MËt V©n §Çu Hoµn", nStoneRequire =  1},
		[1986] = {strName = "Tö M·ng Háa V©n §Çu Hoµn", nStoneRequire =  1},
		[1996] = {strName = "Tö M·ng Dung Kim Kh«i", nStoneRequire =  1},
		[2006] = {strName = "Tö M·ng Liªu Nguyªn Qu¸n MiÖn", nStoneRequire =  1},
		[2016] = {strName = "Tö M·ng Ch©n Nguyªn Qu¸n", nStoneRequire =  1},
		[2026] = {strName = "Tö M·ng Ch©n Vò Qu¸n", nStoneRequire =  1},
		[2036] = {strName = "Tö M·ng §o¹n Thñy §¹o Qu¸n", nStoneRequire =  1},
		[2046] = {strName = "Tö M·ng TrÝch Tinh §¹o Qu¸n", nStoneRequire =  1},
		[1829] = {strName = "Tö M·ng V« T­íng Yªu §¸i", nStoneRequire =  1},
		[1839] = {strName = "Tö M·ng Tø Kh«ng Yªu §¸i", nStoneRequire =  1},
		[1849] = {strName = "Tö M·ng Thanh TÞnh Yªu §¸i", nStoneRequire =  1},
		[1859] = {strName = "Tö M·ng Sïng Minh Yªu §¸i", nStoneRequire =  1},
		[1869] = {strName = "Tö M·ng §Þnh H¶i Yªu §¸i", nStoneRequire =  1},
		[1879] = {strName = "Tö M·ng Tuyªn Uy Yªu §¸i", nStoneRequire =  1},
		[1889] = {strName = "Tö M·ng XuÊt ThÇn Thóc Yªu", nStoneRequire =  1},
		[1899] = {strName = "Tö M·ng Méc TuyÕt Thóc Yªu", nStoneRequire =  1},
		[1909] = {strName = "Tö M·ng Thanh S­¬ng Thóc Yªu", nStoneRequire =  1},
		[1919] = {strName = "Tö M·ng ThÕ H­¬ng Yªu §¸i", nStoneRequire =  1},
		[1929] = {strName = "Tö M·ng Thùc Cèt Yªu §¸i", nStoneRequire =  1},
		[1939] = {strName = "Tö M·ng Xuyªn T©m Yªu §¸i", nStoneRequire =  1},
		[1949] = {strName = "Tö M·ng Lang Nha TriÒn Yªu", nStoneRequire =  1},
		[1959] = {strName = "Tö M·ng Thanh Vô Thóc Yªu", nStoneRequire =  1},
		[1969] = {strName = "Tö M·ng Phong S­¬ng Thóc Yªu", nStoneRequire =  1},
		[1979] = {strName = "Tö M·ng MËt V©n Thóc Yªu", nStoneRequire =  1},
		[1989] = {strName = "Tö M·ng Háa V©n Thóc Yªu", nStoneRequire =  1},
		[1999] = {strName = "Tö M·ng Dung Kim Yªu §¸i", nStoneRequire =  1},
		[2009] = {strName = "Tö M·ng Liªu Nguyªn Yªu §¸i", nStoneRequire =  1},
		[2019] = {strName = "Tö M·ng Ch©n Nguyªn Ph¸p §¸i", nStoneRequire =  1},
		[2029] = {strName = "Tö M·ng Ch©n Vò Ph¸p §¸i", nStoneRequire =  1},
		[2039] = {strName = "Tö M·ng §o¹n Thñy Yªu §¸i", nStoneRequire =  1},
		[2049] = {strName = "Tö M·ng TrÝch Tinh Yªu §¸i", nStoneRequire =  1},
		[1830] = {strName = "Tö M·ng V« T­íng Cµ Sa", nStoneRequire =  2},
		[1840] = {strName = "Tö M·ng Tø Kh«ng Cµ Sa", nStoneRequire =  2},
		[1850] = {strName = "Tö M·ng Thanh TÞnh Cµ Sa", nStoneRequire =  2},
		[1860] = {strName = "Tö M·ng Sïng Minh Kh¶i", nStoneRequire =  2},
		[1870] = {strName = "Tö M·ng §Þnh H¶i Kh¶i", nStoneRequire =  2},
		[1880] = {strName = "Tö M·ng Tuyªn Uy Kh¶i", nStoneRequire =  2},
		[1890] = {strName = "Tö M·ng XuÊt ThÇn Sa Y", nStoneRequire =  2},
		[1900] = {strName = "Tö M·ng Méc TuyÕt Sam", nStoneRequire =  2},
		[1910] = {strName = "Tö M·ng Thanh S­¬ng Sam", nStoneRequire =  2},
		[1920] = {strName = "Tö M·ng ThÕ H­¬ng Sam", nStoneRequire =  2},
		[1930] = {strName = "Tö M·ng Thùc Cèt BÝ Trang", nStoneRequire =  2},
		[1940] = {strName = "Tö M·ng Xuyªn T©m BÝ Trang", nStoneRequire =  2},
		[1950] = {strName = "Tö M·ng Lang Nha Gi¸p Y", nStoneRequire =  2},
		[1960] = {strName = "Tö M·ng Thanh Vô Gi¸p Y", nStoneRequire =  2},
		[1970] = {strName = "Tö M·ng Phong S­¬ng Gi¸p Y", nStoneRequire =  2},
		[1980] = {strName = "Tö M·ng MËt V©n C¸i Y", nStoneRequire =  2},
		[1990] = {strName = "Tö M·ng Háa V©n C¸i Y", nStoneRequire =  2},
		[2000] = {strName = "Tö M·ng Dung Kim Gi¸p", nStoneRequire =  2},
		[2010] = {strName = "Tö M·ng Liªu Nguyªn Gi¸p Y", nStoneRequire =  2},
		[2020] = {strName = "Tö M·ng Ch©n Nguyªn §¹o Bµo", nStoneRequire =  2},
		[2030] = {strName = "Tö M·ng Ch©n Vò §¹o Bµo", nStoneRequire =  2},
		[2040] = {strName = "Tö M·ng §o¹n Thñy §¹o Bµo", nStoneRequire =  2},
		[2050] = {strName = "Tö M·ng TrÝch Tinh §¹o Bµo", nStoneRequire =  2},
		[1832] = {strName = "Tö M·ng V« T­íng T¨ng Hµi", nStoneRequire =  2},
		[1842] = {strName = "Tö M·ng Tø Kh«ng T¨ng Hµi", nStoneRequire =  2},
		[1852] = {strName = "Tö M·ng Thanh TÞnh T¨ng Hµi", nStoneRequire =  2},
		[1862] = {strName = "Tö M·ng Sïng Minh Ngoa", nStoneRequire =  2},
		[1872] = {strName = "Tö M·ng §Þnh H¶i Ngoa", nStoneRequire =  2},
		[1882] = {strName = "Tö M·ng Tuyªn Uy Ngoa", nStoneRequire =  2},
		[1892] = {strName = "Tö M·ng XuÊt ThÇn Hµi", nStoneRequire =  2},
		[1902] = {strName = "Tö M·ng Méc TuyÕt Ngoa", nStoneRequire =  2},
		[1912] = {strName = "Tö M·ng Thanh S­¬ng Ngoa", nStoneRequire =  2},
		[1922] = {strName = "Tö M·ng ThÕ H­¬ng Ngoa", nStoneRequire =  2},
		[1932] = {strName = "Tö M·ng Thùc Cèt Ngoa", nStoneRequire =  2},
		[1942] = {strName = "Tö M·ng Xuyªn T©m Ngoa", nStoneRequire =  2},
		[1952] = {strName = "Tö M·ng Lang Nha Lý", nStoneRequire =  2},
		[1962] = {strName = "Tö M·ng Thanh Vô Lý", nStoneRequire =  2},
		[1972] = {strName = "Tö M·ng Phong S­¬ng Lý", nStoneRequire =  2},
		[1982] = {strName = "Tö M·ng MËt V©n Ngoa", nStoneRequire =  2},
		[1992] = {strName = "Tö M·ng Háa V©n Ngoa", nStoneRequire =  2},
		[2002] = {strName = "Tö M·ng Dung Kim Ngoa", nStoneRequire =  2},
		[2012] = {strName = "Tö M·ng Liªu Nguyªn Ngoa", nStoneRequire =  2},
		[2022] = {strName = "Tö M·ng Ch©n Nguyªn Lý", nStoneRequire =  2},
		[2032] = {strName = "Tö M·ng Ch©n Vò Lý", nStoneRequire =  2},
		[2042] = {strName = "Tö M·ng §o¹n Thñy Ngoa", nStoneRequire =  2},
		[2052] = {strName = "Tö M·ng TrÝch Tinh Ngoa", nStoneRequire =  2},
		[1834] = {strName = "Tö M·ng V« T­íng H¹ Giíi", nStoneRequire =  2},
		[1844] = {strName = "Tö M·ng Tø Kh«ng H¹ Giíi", nStoneRequire =  2},
		[1854] = {strName = "Tö M·ng Thanh TÞnh H¹ Giíi", nStoneRequire =  2},
		[1864] = {strName = "Tö M·ng Sïng Minh H¹ Giíi", nStoneRequire =  2},
		[1874] = {strName = "Tö M·ng §Þnh H¶i H¹ Giíi", nStoneRequire =  2},
		[1884] = {strName = "Tö M·ng Tuyªn Uy H¹ Giíi", nStoneRequire =  2},
		[1894] = {strName = "Tö M·ng XuÊt ThÇn H¹ Giíi", nStoneRequire =  2},
		[1904] = {strName = "Tö M·ng Méc TuyÕt H¹ Giíi", nStoneRequire =  2},
		[1914] = {strName = "Tö M·ng Thanh S­¬ng H¹ Giíi", nStoneRequire =  2},
		[1924] = {strName = "Tö M·ng ThÕ H­¬ng H¹ Giíi", nStoneRequire =  2},
		[1934] = {strName = "Tö M·ng Thùc Cèt H¹ Giíi", nStoneRequire =  2},
		[1944] = {strName = "Tö M·ng Xuyªn T©m H¹ Giíi", nStoneRequire =  2},
		[1954] = {strName = "Tö M·ng Lang Nha H¹ Giíi", nStoneRequire =  2},
		[1964] = {strName = "Tö M·ng Thanh Vô H¹ Giíi", nStoneRequire =  2},
		[1974] = {strName = "Tö M·ng Phong S­¬ng H¹ Giíi", nStoneRequire =  2},
		[1984] = {strName = "Tö M·ng MËt V©n H¹ Giíi", nStoneRequire =  2},
		[1994] = {strName = "Tö M·ng Háa V©n H¹ Giíi", nStoneRequire =  2},
		[2004] = {strName = "Tö M·ng Dung Kim H¹ Giíi", nStoneRequire =  2},
		[2014] = {strName = "Tö M·ng Liªu Nguyªn H¹ Giíi", nStoneRequire =  2},
		[2024] = {strName = "Tö M·ng Ch©n Nguyªn H¹ Giíi", nStoneRequire =  2},
		[2034] = {strName = "Tö M·ng Ch©n Vò H¹ Giíi", nStoneRequire =  2},
		[2044] = {strName = "Tö M·ng §o¹n Thñy H¹ Giíi", nStoneRequire =  2},
		[2054] = {strName = "Tö M·ng TrÝch Tinh H¹ Giíi", nStoneRequire =  2},
		[1825] = {strName = "Tö M·ng V« T­íng Ch©u LiÖm", nStoneRequire =  2},
		[1835] = {strName = "Tö M·ng Tø Kh«ng PhËt Ch©u", nStoneRequire =  2},
		[1845] = {strName = "Tö M·ng Thanh TÞnh H¹ng LiÖm", nStoneRequire =  2},
		[1855] = {strName = "Tö M·ng Sïng Minh LiÖm", nStoneRequire =  2},
		[1865] = {strName = "Tö M·ng §Þnh H¶i H¹ng LiÖm", nStoneRequire =  2},
		[1875] = {strName = "Tö M·ng Tuyªn Uy H¹ng LiÖm", nStoneRequire =  2},
		[1885] = {strName = "Tö M·ng XuÊt ThÇn Ch©u LiÖm", nStoneRequire =  2},
		[1895] = {strName = "Tö M·ng Méc TuyÕt Ch©u LiÖm", nStoneRequire =  2},
		[1905] = {strName = "Tö M·ng Thanh S­¬ng Ch©u LiÖm", nStoneRequire =  2},
		[1915] = {strName = "Tö M·ng ThÕ H­¬ng Ch©u LiÖm", nStoneRequire =  2},
		[1925] = {strName = "Tö M·ng Thùc Cèt H¹ng LiÖm", nStoneRequire =  2},
		[1935] = {strName = "Tö M·ng Xuyªn T©m H¹ng LiÖm", nStoneRequire =  2},
		[1945] = {strName = "Tö M·ng Lang Nha H¹ng LiÖm", nStoneRequire =  2},
		[1955] = {strName = "Tö M·ng Thanh Vô H¹ng LiÖm", nStoneRequire =  2},
		[1965] = {strName = "Tö M·ng Phong S­¬ng H¹ng LiÖm", nStoneRequire =  2},
		[1975] = {strName = "Tö M·ng MËt V©n H¹ng LiÖm", nStoneRequire =  2},
		[1985] = {strName = "Tö M·ng Háa V©n H¹ng LiÖm", nStoneRequire =  2},
		[1995] = {strName = "Tö M·ng Dung Kim H¹ng Khuyªn", nStoneRequire =  2},
		[2005] = {strName = "Tö M·ng Liªu Nguyªn H¹ng LiÖm", nStoneRequire =  2},
		[2015] = {strName = "Tö M·ng Ch©n Nguyªn Phï", nStoneRequire =  2},
		[2025] = {strName = "Tö M·ng Ch©n Vò Phï", nStoneRequire =  2},
		[2035] = {strName = "Tö M·ng §o¹n Thñy H¹ng LiÖm", nStoneRequire =  2},
		[2045] = {strName = "Tö M·ng TrÝch Tinh Phï", nStoneRequire =  2},
		[1827] = {strName = "Tö M·ng V« T­íng Th­îng Giíi", nStoneRequire =  2},
		[1837] = {strName = "Tö M·ng Tø Kh«ng Th­îng Giíi", nStoneRequire =  2},
		[1847] = {strName = "Tö M·ng Thanh TÞnh Th­îng Giíi", nStoneRequire =  2},
		[1857] = {strName = "Tö M·ng Sïng Minh Th­îng Giíi", nStoneRequire =  2},
		[1867] = {strName = "Tö M·ng §Þnh H¶i Th­îng Giíi", nStoneRequire =  2},
		[1877] = {strName = "Tö M·ng Tuyªn Uy Th­îng Giíi", nStoneRequire =  2},
		[1887] = {strName = "Tö M·ng XuÊt ThÇn Th­îng Giíi", nStoneRequire =  2},
		[1897] = {strName = "Tö M·ng Méc TuyÕt Th­îng Giíi", nStoneRequire =  2},
		[1907] = {strName = "Tö M·ng Thanh S­¬ng Th­îng Giíi", nStoneRequire =  2},
		[1917] = {strName = "Tö M·ng ThÕ H­¬ng Th­îng Giíi", nStoneRequire =  2},
		[1927] = {strName = "Tö M·ng Thùc Cèt Th­îng Giíi", nStoneRequire =  2},
		[1937] = {strName = "Tö M·ng Xuyªn T©m Th­îng Giíi", nStoneRequire =  2},
		[1947] = {strName = "Tö M·ng Lang Nha Th­îng Giíi", nStoneRequire =  2},
		[1957] = {strName = "Tö M·ng Thanh Vô Th­îng Giíi", nStoneRequire =  2},
		[1967] = {strName = "Tö M·ng Phong S­¬ng Th­îng Giíi", nStoneRequire =  2},
		[1977] = {strName = "Tö M·ng MËt V©n Th­îng Giíi", nStoneRequire =  2},
		[1987] = {strName = "Tö M·ng Háa V©n Th­îng Giíi", nStoneRequire =  2},
		[1997] = {strName = "Tö M·ng Dung Kim Th­îng Giíi", nStoneRequire =  2},
		[2007] = {strName = "Tö M·ng Liªu Nguyªn Th­îng Giíi", nStoneRequire =  2},
		[2017] = {strName = "Tö M·ng Ch©n Nguyªn Th­îng Giíi", nStoneRequire =  2},
		[2027] = {strName = "Tö M·ng Ch©n Vò Th­îng Giíi", nStoneRequire =  2},
		[2037] = {strName = "Tö M·ng §o¹n Thñy Th­îng Giíi", nStoneRequire =  2},
		[2047] = {strName = "Tö M·ng TrÝch Tinh Th­îng Giíi", nStoneRequire =  2},
		[1833] = {strName = "Tö M·ng V« T­íng Yªu Trôy", nStoneRequire =  2},
		[1843] = {strName = "Tö M·ng Tø Kh«ng Yªu Trôy", nStoneRequire =  2},
		[1853] = {strName = "Tö M·ng Thanh TÞnh Yªu Trôy", nStoneRequire =  2},
		[1863] = {strName = "Tö M·ng Sïng Minh Béi", nStoneRequire =  2},
		[1873] = {strName = "Tö M·ng §Þnh H¶i Yªu Trôy", nStoneRequire =  2},
		[1883] = {strName = "Tö M·ng Tuyªn Uy Yªu Trôy", nStoneRequire =  2},
		[1893] = {strName = "Tö M·ng XuÊt ThÇn H­¬ng Nang", nStoneRequire =  2},
		[1903] = {strName = "Tö M·ng Méc TuyÕt H­¬ng Nang", nStoneRequire =  2},
		[1913] = {strName = "Tö M·ng Thanh S­¬ng H­¬ng Nang", nStoneRequire =  2},
		[1923] = {strName = "Tö M·ng ThÕ H­¬ng H­¬ng Nang", nStoneRequire =  2},
		[1933] = {strName = "Tö M·ng Thùc Cèt Yªu Trôy", nStoneRequire =  2},
		[1943] = {strName = "Tö M·ng Xuyªn T©m Yªu Trôy", nStoneRequire =  2},
		[1953] = {strName = "Tö M·ng Lang Nha Yªu Trôy", nStoneRequire =  2},
		[1963] = {strName = "Tö M·ng Thanh Vô Trôy", nStoneRequire =  2},
		[1973] = {strName = "Tö M·ng Phong S­¬ng Yªu Trôy", nStoneRequire =  2},
		[1983] = {strName = "Tö M·ng MËt V©n Yªu Trôy", nStoneRequire =  2},
		[1993] = {strName = "Tö M·ng Háa V©n Yªu Trôy", nStoneRequire =  2},
		[2003] = {strName = "Tö M·ng Dung Kim Béi", nStoneRequire =  2},
		[2013] = {strName = "Tö M·ng Liªu Nguyªn Béi", nStoneRequire =  2},
		[2023] = {strName = "Tö M·ng Ch©n Nguyªn Ngäc Béi", nStoneRequire =  2},
		[2033] = {strName = "Tö M·ng Ch©n Vò Ngäc Béi", nStoneRequire =  2},
		[2043] = {strName = "Tö M·ng §o¹n Thñy Béi", nStoneRequire =  2},
		[2053] = {strName = "Tö M·ng TrÝch Tinh Béi", nStoneRequire =  2},
		[1831] = {strName = "Tö M·ng V« T­íng TriÒn Thñ", nStoneRequire =  3},
		[1841] = {strName = "Tö M·ng Tø Kh«ng T¨ng C«n", nStoneRequire =  3},
		[1851] = {strName = "Tö M·ng Thanh TÞnh Giíi §ao", nStoneRequire =  3},
		[1861] = {strName = "Tö M·ng Sïng Minh Chïy", nStoneRequire =  3},
		[1871] = {strName = "Tö M·ng §Þnh H¶i Th­¬ng", nStoneRequire =  3},
		[1881] = {strName = "Tö M·ng Tuyªn Uy B¶o §ao", nStoneRequire =  3},
		[1891] = {strName = "Tö M·ng XuÊt ThÇn KiÕm", nStoneRequire =  3},
		[1901] = {strName = "Tö M·ng Méc TuyÕt TriÒn Thñ", nStoneRequire =  3},
		[1911] = {strName = "Tö M·ng Thanh S­¬ng §ao", nStoneRequire =  3},
		[1921] = {strName = "Tö M·ng ThÕ H­¬ng Uyªn ¦¬ng §ao", nStoneRequire =  3},
		[1931] = {strName = "Tö M·ng Thùc Cèt TriÒn Thñ", nStoneRequire =  3},
		[1941] = {strName = "Tö M·ng Xuyªn T©m §ao", nStoneRequire =  3},
		[1951] = {strName = "Tö M·ng Lang Nha Phi §ao", nStoneRequire =  3},
		[1961] = {strName = "Tö M·ng Thanh Vô TôTiÔn", nStoneRequire =  3},
		[1971] = {strName = "Tö M·ng Phong S­¬ng Tiªu", nStoneRequire =  3},
		[1981] = {strName = "Tö M·ng MËt V©n TriÒn Thñ", nStoneRequire =  3},
		[1991] = {strName = "Tö M·ng Háa V©n Tr­îng", nStoneRequire =  3},
		[2001] = {strName = "Tö M·ng Dung Kim Th­¬ng", nStoneRequire =  3},
		[2011] = {strName = "Tö M·ng Liªu Nguyªn §ao", nStoneRequire =  3},
		[2021] = {strName = "Tö M·ng Ch©n Nguyªn KiÕm", nStoneRequire =  3},
		[2031] = {strName = "Tö M·ng Ch©n Vò KiÕm", nStoneRequire =  3},
		[2041] = {strName = "Tö M·ng §o¹n Thñy §ao", nStoneRequire =  3},
		[2051] = {strName = "Tö M·ng TrÝch Tinh KiÕm", nStoneRequire =  3},
	}