MSG_MENU_NPC = "NhËn phÇn th­ëng VIP"
MSG_IS_NOT_VIP = "Xin lçi! §¹i hiÖp kh«ng ®ñ ®iÒu kiÖn nhËn th­ëng"
MSG_ALREADY_RECEIVED_AWARD = "§¹i hiÖp ®· nhËn th­ëng tuÇn nµy råi"
MSG_NOT_ENOUGH_BAG_CELL = "§Ó an toµn, Xin h·y chõa 5 « trèng trong hµnh trang råi míi nhËn th­ëng"
 MSG_RECEIVE_GOLD_AWARD ="Chóc mõng b¹n ®· nhËn ®­îc phÇn th­ëng <color=yellow>Vip Vµng<color>"
 MSG_RECEIVE_GOLD_TITLE = "Chóc mõng b¹n ®· nhËn ®­îc danh hiÖu <color=yellow>%s<color>"
 MSG_RECEIVE_SILVER_AWARD = "Chóc mõng b¹n ®· nhËn ®­îc phÇn th­ëng <color=yellow>Vip B¹c<color>"
 MSG_RECEIVE_BRONZE_AWARD = "Chóc mõng b¹n ®· nhËn ®­îc phÇn th­ëng <color=yellow>Vip §ång<color>"
LOG_TITLE = "TraoThuongVip2013"
