
-- 2006/04/29 ÎªÔ½ÄÏ°æÐÞ¸ÄÊ¦¸µÊÕÍ½µÜÏÞÖÆ£¬ÆßÌìÖ»ÄÜÊÕÎå¸ö¡£   by peres

TTKID_APPRENTICE_FLAG = 20 --°ÝÊ¦ÇëÇó±êÊ¶
TTKID_RECRUIT_FLAG = 21 --ÊÕÍ½ÇëÇó±êÊ¶
TTKID_SELF_LILIAN_FLAG = 22 --Í½µÜÇëÇó¸´Ãü±êÊ¶
TTKID_MASTER_LILIAN_FLAG = 23 --Ê¦¸¸ÇëÇó²é¿´±êÊ¶
TTKID_APPRENTICE_CHUSHI = 24 --Í½µÜ³öÊ¦ÇëÇó±êÊ¶
TTKID_MASTER_CHUSHI = 25 --Ê¦¸¸ÒªÇó³öÊ¦ÇëÇó±êÊ¶

TKID_APPLY_JOIN_LEAGUE = 1400
TKID_APPLY_GRADUATE = 1401
TKID_MASTER_COUNT = 1402 --°ÝÊ¦×ÜÊý
TKID_APPRENTICE_COUNT = 1403 --ÊÕÍ½µÜ×ÜÊý
TKID_ENTER_LEVEL = 1404 --°ÝÊ¦Ê±µÄµÈ¼¶
TKID_CHUSHI_MASTER_BONUS = 1405  --³öÊ¦Ê±Ê¦¸¸µÄ½±Àø
TKID_CHUSHI_APPRENTICE_BONUS = 1406  --³öÊ¦Ê¦Í½µÜµÄ½±Àø
TKID_CHUSHI_DICHUAN_BONUS = 1407 --µÕ´«µÜ×Ó¶îÍâ½±Àø
TKID_CHUSHI_ZHIXI_BONUS = 1408 --Ö±ÏµµÜ×Ó¶îÍâ½±Àø
TKID_DICHUAN_APPRENTICE_COUNT = 1409 --µÕ´«µÜ×ÓÊý
TKID_ZHIXI_APPRENTICE_COUNT = 1410 --Ö±ÏµµÜ×ÓÊý
TKID_NORMAL_APPRENTICE_COUNT = 1411 --ÆÕÍ¨µÜ×ÓÊý

TKID_LAST_SHITU_OPERATION = 1412 --ÉÏÒ»´Î¶ÔLeague²Ù×÷µÄID
TKID_LAST_SHITU_DATA1=	1413
TKID_LAST_SHITU_DATA2=	1414
TKID_MASTER_BREAK_TIME = 1415 --×îºóÒ»´ÎÊ¦¸¸½â³ýÊ¦Í½¹ØÏµµÄÊ±¼ä
TKID_APPRENTICE_BREAK_TIME = 1416 --×îºóÒ»´ÎÍ½µÜ½â³ýÊ¦Í½¹ØÏµµÄÊ±¼ä

TKID_GOLD_APPRENTICE = 1399 -- »Æ½ðÍ½µÜ(0 - ÆÕÍ¨£¬1 - Î´·¢¹ý°ÝÊ¦¹«¸æ£¬2 - ·¢¹ý°ÝÊ¦¹«¸æ)

CONST_BREAKSHITU_PROTECTEDTIME = 24*60*60 -- ½â³ýÊ¦Í½¹ØÏµÇ°µÄ±£»¤Ê±¼ä (Ãë)
CONST_SHITU_TU_TITLEID = 30	-- Í½µÜµÄ³ÆºÅ

CONST_BONUS_COUNT_APPRENTICE = 2
CONST_LEAGUEJOB_MASTER = 1
CONST_LEAGUEJOB_APPRENTICE = 2
CONST_LEAGUETYPE_SHITU = 1
CONST_DEGREE_MASTER = CONST_LEAGUEJOB_MASTER
CONST_DEGREE_APPRENTICE = CONST_LEAGUEJOB_APPRENTICE
CONST_DEGREE_PREAPPRENTICE = 3
CONST_DEGREE_PREMASTER = 4


CONST_OPER_JOINSHITU = 1;
CONST_OPER_GRADUATE= 2;
CONST_OPER_LEAVESHITU = 3;


TKID_SELF_LILIAN = 1450 --¸öÈËÀúÁ·µÄÁÐ±í
TKID_MASTER_LILIAN = 1460 --ÔÚÊ¦¸¸ÃûÏÂµÄÀúÁ·ÁÐ±í
TKID_BONUS_LILIAN = 1470 --ÀúÁ·µÄ·¢½±ÁÐ±í

ID_SHITU_LIMIT_DATE = 2417  -- Ô½ÄÏÊ¦Í½ÏµÍ³¼ÇÂ¼ÏÞÖÆÈÕÆÚ
ID_SHITU_LIMIT_NUM  = 2418  -- Ô½ÄÏÊ¦Í½ÏµÍ³¼ÇÂ¼ÏÞÖÆÊýÁ¿

CONST_SHITU_LIMIT_TIME    = 60 * 60 * 24 * 7  -- ÆßÌìÏÞÖÆµÄÃëÊý×ÜÊý

CONST_LILIAN_MEM_WIDTH = 4

CONST_LLITEM_JOINPARTY = 1
CONST_LLITEM_YESOUTASK = 2
CONST_LLITEM_ZHENGPAI20 = 3
CONST_LLITEM_ZHONGLI20 = 4
CONST_LLITEM_XIEPAI20 = 5
CONST_LLITEM_ZHENGPAI30 = 6
CONST_LLITEM_ZHONGLI30 = 7
CONST_LLITEM_XIEPAI30 = 8
CONST_LLITEM_ZHENGPAI40 = 9
CONST_LLITEM_ZHONGLI40 = 10
CONST_LLITEM_XIEPAI40 = 11
CONST_LLITEM_ZHENGPAI50 = 12
CONST_LLITEM_ZHONGLI50 = 13
CONST_LLITEM_XIEPAI50 = 14
CONST_LLITEM_ZHENGPAI60 = 15
CONST_LLITEM_ZHONGLI60 = 16
CONST_LLITEM_XIEPAI60 = 17
CONST_LLITEM_SONGJIN = 18
CONST_LLITEM_GETSKILL60 = 19
CONST_LLITEM_LEVEL65 = 20
CONST_LLITEM_LEVEL70 = 21
CONST_LLITEM_LEVEL75 = 22
CONST_LLITEM_LEVEL76 = 23
CONST_LLITEM_LEVEL77 = 24
CONST_LLITEM_LEVEL78 = 25
CONST_LLITEM_LEVEL79 = 26
CONST_LLITEM_LEVEL80 = 27
CONST_LLITEM_SKILL10UP5 = 28
CONST_LLITEM_SKILL10UP15 = 29
CONST_LLITEM_GETSKILL30 = 30
CONST_LLITEM_GETSKILL40 = 31
CONST_LLITEM_GETSKILL50 = 32
CONST_LLITEM_SKILL60UP3 = 33
CONST_LLITEM_JOINTONG = 34
CONST_LLITEM_SHENGWANG = 35
CONST_LLITEM_SHANHESHEJI = 36
LILIAN_ITEM = {
	[CONST_LLITEM_JOINPARTY] = "B¸i nhËp 1 m«n ph¸i",
	[CONST_LLITEM_YESOUTASK] = "Liªn tiÕp hoµn thµnh 10 lÇn nhiÖm vô D· tÈu trë lªn",
	[CONST_LLITEM_ZHENGPAI20] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn ChÝnh ph¸i cÊp 20",
	[CONST_LLITEM_ZHONGLI20] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Trung lËp cÊp 20",
	[CONST_LLITEM_XIEPAI20] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Tµ ph¸i cÊp 20",
	[CONST_LLITEM_ZHENGPAI30] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn ChÝnh ph¸i cÊp 30",
	[CONST_LLITEM_ZHONGLI30] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Trung lËp cÊp 30",
	[CONST_LLITEM_XIEPAI30] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Tµ ph¸i cÊp 30",
	[CONST_LLITEM_ZHENGPAI40] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn ChÝnh ph¸i cÊp 40",
	[CONST_LLITEM_ZHONGLI40] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Trung lËp cÊp 40",
	[CONST_LLITEM_XIEPAI40] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Tµ ph¸i cÊp 40",
	[CONST_LLITEM_ZHENGPAI50] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn ChÝnh ph¸i cÊp 50",
	[CONST_LLITEM_ZHONGLI50] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Trung lËp cÊp 50",
	[CONST_LLITEM_XIEPAI50] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Tµ ph¸i cÊp 50",
	[CONST_LLITEM_ZHENGPAI60] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn ChÝnh ph¸i cÊp 60",
	[CONST_LLITEM_ZHONGLI60] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Trung lËp cÊp 60",
	[CONST_LLITEM_XIEPAI60] = "Hoµn thµnh nhiÖm vô ChÝnh tuyÕn Tµ ph¸i cÊp 60",
	[CONST_LLITEM_SONGJIN] = "§¹t ®­îc 1000 ®iÓm th­ëng Tèng Kim trë lªn.",
	[CONST_LLITEM_GETSKILL60] = "Häc ®­îc vâ c«ng cÊp 60 cña Bæn m«n",
	[CONST_LLITEM_LEVEL65] = "§¼ng cÊp trªn 65",
	[CONST_LLITEM_LEVEL70] = "§¼ng cÊp trªn 70",
	[CONST_LLITEM_LEVEL75] = "§¼ng cÊp trªn 75",
	[CONST_LLITEM_LEVEL76] = "§¼ng cÊp trªn 76",
	[CONST_LLITEM_LEVEL77] = "§¼ng cÊp trªn 77",
	[CONST_LLITEM_LEVEL78] = "§¼ng cÊp trªn 78",
	[CONST_LLITEM_LEVEL79] = "§¼ng cÊp trªn 79",
	[CONST_LLITEM_LEVEL80] = "§¼ng cÊp trªn 80",
	[CONST_LLITEM_SKILL10UP5] = "Kü n¨ng cÊp 10 cña bæn m«n ®· t¨ng ®Õn cÊp 5",
	[CONST_LLITEM_SKILL10UP15] = "Kü n¨ng cÊp 10 cña bæn m«n ®· t¨ng ®Õn cÊp 15",
	[CONST_LLITEM_GETSKILL30] = "Häc ®­îc vâ c«ng cÊp 30 cña Bæn m«n",
	[CONST_LLITEM_GETSKILL40] = "Häc ®­îc vâ c«ng cÊp 40 cña Bæn m«n",
	[CONST_LLITEM_GETSKILL50] = "Häc ®­îc vâ c«ng cÊp 50 cña Bæn m«n",
	[CONST_LLITEM_SKILL60UP3] = "Kü n¨ng cÊp 60 cña bæn m«n ®· t¨ng ®Õn cÊp 3",
	[CONST_LLITEM_JOINTONG] = "Gia nhËp 1 Bang ph¸i",
	[CONST_LLITEM_SHENGWANG] = "§¹t ®­îc 200 ®iÓm Danh väng trë lªn",
	[CONST_LLITEM_SHANHESHEJI] = "LÊy ®­îc 500 tÊm b¶n ®å S¬n hµ x· t¾c trë lªn.",
}

CONST_PARTY_SHAOLIN = 0
CONST_PARTY_TIANWANG = 1
CONST_PARTY_TANGMEN = 2
CONST_PARTY_WUDU = 3
CONST_PARTY_EMEI = 4
CONST_PARTY_CUIYAN = 5
CONST_PARTY_GAIBANG = 6
CONST_PARTY_TIANREN = 7
CONST_PARTY_WUDANG = 8
CONST_PARTY_KUNLUN = 9
CONST_PARTY_NOT = -1
CONST_SKILL_LUOHANZHEN = 16	--ÂÞººÕó
CONST_SKILL_SHIZIHOU = 20	--Ê¨×Óºð
CONST_SKILL_LONGZHAOHUZHUA = 271	--Áú×¦»¢×¥
CONST_SKILL_HENGSAOLIUHE = 11	--ºáÉ¨ÁùºÏ
CONST_SKILL_MOHEWULIANG = 19	--Ä¦Ú­ÎÞÁ¿
CONST_SKILL_YIJINJING = 21	--Ò×½î¾­
CONST_SKILL_POFENGZHAN = 37	--ÆÃ·çÕ¶
CONST_SKILL_YANGGUANSANDIE = 35	--Ñô¹ØÈýµþ
CONST_SKILL_XINGYUNJUE = 31	--ÐÐÔÆ¾÷
CONST_SKILL_DUANHUNCI = 40	--¶Ï»ê´Ì
CONST_SKILL_JINZHONGZHAO = 42	--½ðÖÓÕÖ
CONST_SKILL_TIANWANGZHANYI = 36	--ÌìÍõÕ½Òâ
CONST_SKILL_WUXINZHAN= 32	--ÎÞÐÄÕ¶
CONST_SKILL_XUEZHANBAFANG = 41	--ÑªÕ½°Ë·½
CONST_SKILL_CHENGLONGJUE = 324	--³ËÁú¾÷
CONST_SKILL_ZHUIXINJIAN = 50	--×·ÐÄ¼ý
CONST_SKILL_MANTIANHUAYU = 54	--ÂþÌì»¨Óê
CONST_SKILL_DUOHUNBIAO = 47	--¶á»êïÚ
CONST_SKILL_CHUANXINCI = 343	--´©ÐÄ´Ì
CONST_SKILL_HANBINGCI = 345	---º®±ù´Ì
CONST_SKILL_LEIJISHU = 349	--À×»÷Êõ
CONST_SKILL_XINYAN = 48	--ÐÄÑÛ
CONST_SKILL_XIAOLIFEIDAO = 249	--Ð¡Àî·Éµ¶
CONST_SKILL_TIANLUODIWANG = 58	--ÌìÂÞµØÍø
CONST_SKILL_SANHUABIAO = 341	--É¢»¨ïÚ
CONST_SKILL_YOUMINGKULOU = 68	--ÓÄÚ¤÷¼÷Ã
CONST_SKILL_BAIDUCHUANXIN = 384	--°Ù¶¾´©ÐÄ
CONST_SKILL_BINGLANXUANJING = 64	--±ùÀ¶Ðþ¾§
CONST_SKILL_WUXINGGU = 69	--ÎÞÐÎ¹Æ
CONST_SKILL_CHUANYIPOJIA = 356	--´©ÒÂÆÆ¼×
CONST_SKILL_WANGUSHIXIN = 73	--Íò¹ÆÊ´ÐÄ
CONST_SKILL_CHUANXINDUCI = 72	--´©ÐÄ¶¾´Ì
CONST_SKILL_WUDUQIJING = 75	--Îå¶¾Ææ¾­
CONST_SKILL_TIANGANGDISHA = 71	--Ììî¸µØÉ·
CONST_SKILL_ZHUHAQINGMING = 74	--Öì¸òÇàÚ¤
CONST_SKILL_TUICHUANGWANGYUE = 385	--ÍÆ´°ÍûÔÂ
CONST_SKILL_SIXIANGTONGGUI = 82	--ËÄÏóÍ¬¹é
CONST_SKILL_MENGDIE = 89	--ÃÎµû
CONST_SKILL_LIUSHUI = 86	--Á÷Ë®
CONST_SKILL_FOXINCIYOU = 92	--·ðÐÄ´ÈÓÓ
CONST_SKILL_FOFAWUBIAN = 252	--·ð·¨ÎÞ±ß
CONST_SKILL_BUMIEBUJUE = 88	--²»Ãð²»¾ø
CONST_SKILL_FOGUANGPUZHAO = 91	--·ð¹âÆÕÕÕ
CONST_SKILL_QINGXINFANCHANG = 282	--ÇåÒôèó³ª
CONST_SKILL_YUDALIHUA = 105	--Óê´òÀæ»¨
CONST_SKILL_FUYUNSANXUE = 113	--¸¡ÔÆÉ¢Ñ©
CONST_SKILL_TUTIHANBING = 100	--»¤Ìåº®±ù
CONST_SKILL_XUEYING = 109	--Ñ©Ó°
CONST_SKILL_BINGGUXUEXIN = 114	--±ù¹ÇÑ©ÐÄ
CONST_SKILL_MUYELIUXING = 108	--ÄÁÒ°Á÷ÐÇ
CONST_SKILL_BIHAICHAOSHENG = 111	--±Ìº£³±Éú
CONST_SKILL_XIANGLONGZHANG = 274	--½µÁúÕÆ
CONST_SKILL_DAGOUBANG = 124	--´ò¹·Õó
CONST_SKILL_HUABULIUSHOU = 277	--»¬²»ÁôÊÖ
CONST_SKILL_KANGLONGYOUHUI = 128	--¿ºÁúÓÐ»Ú
CONST_SKILL_BANGDAEGOU = 125	--°ô´ò¶ñ¹·
CONST_SKILL_ZUIDIEKUANGWU = 130	--×íµû¿ñÎè
CONST_SKILL_XIAOYAOGONG = 360	--åÐÒ£¹¦
CONST_SKILL_LIEHONGQINGTIAN = 141	--ÁÒ»ðÇéÌì
CONST_SKILL_TUISHANTIANHAI = 138	--ÍÆÉ½Ìîº£
CONST_SKILL_FEIHONGWUJI = 140	--·ÉºèÎÞ¼£
CONST_SKILL_BEISUQINGFENG = 364	--±¯ËÖÇå·ç
CONST_SKILL_LIMODUOPO = 143	--À÷Ä§¶á»ê
CONST_SKILL_TIANMOJIETIE = 150	--ÌìÄ§½âÌå
CONST_SKILL_TOUTIANHUANRI = 142	--ÍµÌì»»ÈÕ
CONST_SKILL_MOYANQISHA = 148	--Ä§ÑæÆßÉ±
CONST_SKILL_BOJIERFU = 164	--°þ¼°¶ø¸´
CONST_SKILL_JIANFEIJINGTIAN = 158	--½£·É¾ªÌì
CONST_SKILL_TIYUNZONG = 160	--ÌÝÔÆ×Ý
CONST_SKILL_ZUOWANGWUWO = 157	--×øÍüÎÞÎÒ
CONST_SKILL_TAIJISHENGONG = 166	--Ì«¼«Éñ¹¦
CONST_SKILL_WUWOWUJIAN = 165	--ÎÞÎÒÎÞ½£
CONST_SKILL_SANHUANTAOYUE = 267	--Èý»·Ì×ÔÂ
CONST_SKILL_YIQISANQING = 178	--Ò»ÆøÈýÇå
CONST_SKILL_TIANJIXUNLEI = 172	--Ìì¼ÊÑ¸À×
CONST_SKILL_BEIMINGDAOHAI = 393	--±±Ú¤µ½º£
CONST_SKILL_TIANQINGDIZUO = 173	--ÌìÇåµØ×Ç
CONST_SKILL_QIHANAOXUE = 175	--ÆÛº®°ÁÑ©
CONST_SKILL_QIXINFU = 181	--ÆúÐÄ·û
CONST_SKILL_KUANGFENGZHOUDIAN = 176	--¿ñ·çÖèµç
CONST_SKILL_MIZONGHUANGYING = 90	--ÃÔ×Ù»ÃÓ°
CONST_SKILL_SHUANGAOKUNLUN = 275	--Ëª°ÁÀ¥ÂØ
CONST_SKILL_WULEIZHENGFA = 182	--ÎåÀ×Õý·¨
CONST_SKILL_SHAOLINQUANFA = 8	--ÉÙÁÖÈ­·¨
CONST_SKILL_SHAOLINGUNFA = 4	--ÉÙÁÖ¹÷·¨
CONST_SKILL_SHAOLINDAOFA = 6	--ÉÙÁÖµ¶·¨
CONST_SKILL_TIANWANGCHUIFA = 26	--ÌìÍõ´¸·¨
CONST_SKILL_TIANWANGQIANGFA = 23	--ÌìÍõÇ¹·¨
CONST_SKILL_TIANWANGDAOFA = 24	--ÌìÍõµ¶·¨
CONST_SKILL_TANGMENANQI = 43	--ÌÆÃÅ°µÆ÷
CONST_SKILL_DIYANHUO = 347	--µØÑæ»ð
CONST_SKILL_WUDUZHANGFA = 62	--Îå¶¾ÕÆ·¨
CONST_SKILL_WUDUDAOFA = 60	--Îå¶¾µ¶·¨
CONST_SKILL_JIUTIANKUANGLEI = 67	--¾ÅÌì¿ñÀ×
CONST_SKILL_EMEIJIANFA = 77	--¶ëáÒ½£·¨
CONST_SKILL_EMEIZHANGFA = 79	--¶ëáÒÕÆ·¨
CONST_SKILL_CUIYANDAOFA = 95	--´äÑÌµ¶·¨
CONST_SKILL_CUIYANSHUANGDAO = 97	--´äÑÌË«µ¶
CONST_SKILL_GAIBANGZHANGFA = 116	--Ø¤°ïÕÆ·¨
CONST_SKILL_GAIBANGBANGFA = 115	--Ø¤°ï°ô·¨
CONST_SKILL_TIANRENMAOFA = 132	--ÌìÈÌÃ¬·¨
CONST_SKILL_TIANRENDAOFA = 131	--ÌìÈÌµ¶·¨
CONST_SKILL_HUOLIANFENHUA = 136	--»ðÁ«·Ù»ª
CONST_SKILL_WUDANGQUANFA = 152	--Îäµ±È­·¨
CONST_SKILL_WUDANGJIANFA = 151	--Îäµ±½£·¨
CONST_SKILL_KUNLUNDAOFA = 167	--À¥ÂØµ¶·¨
CONST_SKILL_KUNLUNJIANFA = 168	--À¥ÂØ½£·¨
CONST_SKILL_SHUFUZHOU = 392	--Êø¸¿Öä
CONST_SKILL_QINGFENGFU = 171	--Çå·ç·û

SKILLS = {
	[CONST_PARTY_SHAOLIN+1]={
		[10]={	
						CONST_SKILL_SHAOLINQUANFA,
						CONST_SKILL_SHAOLINGUNFA,
						CONST_SKILL_SHAOLINDAOFA
					},
		[30]={CONST_SKILL_LUOHANZHEN},
		[40]={CONST_SKILL_SHIZIHOU},
		[50]={
						CONST_SKILL_LONGZHAOHUZHUA,
						CONST_SKILL_HENGSAOLIUHE,
						CONST_SKILL_MOHEWULIANG},
		[60]={CONST_SKILL_YIJINJING}
	},
	[CONST_PARTY_TIANWANG+1] = {
		[10]={	
						CONST_SKILL_TIANWANGCHUIFA,
						CONST_SKILL_TIANWANGQIANGFA,
						CONST_SKILL_TIANWANGDAOFA
					},
		[30]={
						CONST_SKILL_POFENGZHAN,
						CONST_SKILL_YANGGUANSANDIE,
						CONST_SKILL_XINGYUNJUE
					},
		[40]={CONST_SKILL_DUANHUNCI},
		[50]={CONST_SKILL_JINZHONGZHAO},
		[60]={
						CONST_SKILL_WUXINZHAN,
						CONST_SKILL_XUEZHANBAFANG,
						CONST_SKILL_CHENGLONGJUE
					}
	},
	[CONST_PARTY_TANGMEN+1] = {
		[10]={
						CONST_SKILL_TANGMENANQI,
						CONST_SKILL_DIYANHUO
					},
		[30]={
						CONST_SKILL_ZHUIXINJIAN,
						CONST_SKILL_MANTIANHUAYU,
						CONST_SKILL_DUOHUNBIAO,
						CONST_SKILL_CHUANXINCI
					},
		[40]={CONST_SKILL_HANBINGCI},
		[50]={CONST_SKILL_LEIJISHU},
		[60]={
						CONST_SKILL_XIAOLIFEIDAO,
						CONST_SKILL_TIANLUODIWANG,
						CONST_SKILL_SANHUABIAO
					}
	},
	[CONST_PARTY_WUDU+1] = {
		[10]={
						CONST_SKILL_WUDUZHANGFA,
						CONST_SKILL_WUDUDAOFA,
						CONST_SKILL_JIUTIANKUANGLEI
					},
		[30]={
						CONST_SKILL_YOUMINGKULOU,
						CONST_SKILL_BAIDUCHUANXIN,
						CONST_SKILL_BINGLANXUANJING,
						CONST_SKILL_WUXINGGU
					},
		[40]={
						CONST_SKILL_CHUANYIPOJIA,
						CONST_SKILL_WANGUSHIXIN
					},
		[50]={CONST_SKILL_CHUANXINDUCI},
		[60]={	
						CONST_SKILL_TIANGANGDISHA,
						CONST_SKILL_ZHUHAQINGMING
					}
	},
	[CONST_PARTY_EMEI+1] = {
		[10]={
						CONST_SKILL_EMEIJIANFA,
						CONST_SKILL_EMEIZHANGFA
					},
		[30]={
						CONST_SKILL_TUICHUANGWANGYUE,
						CONST_SKILL_SIXIANGTONGGUI,
						CONST_SKILL_MENGDIE
					},
		[40]={CONST_SKILL_LIUSHUI},
		[50]={CONST_SKILL_FOXINCIYOU},
		[60]={
						CONST_SKILL_BUMIEBUJUE,
						CONST_SKILL_FOGUANGPUZHAO,
						CONST_SKILL_QINGXINFANCHANG
					}
	},
	[CONST_PARTY_CUIYAN+1] = {
		[10]={
						CONST_SKILL_CUIYANDAOFA,
						CONST_SKILL_CUIYANSHUANGDAO
					},
		[30]={
						CONST_SKILL_YUDALIHUA,
						CONST_SKILL_FUYUNSANXUE
					},
		[40]={CONST_SKILL_TUTIHANBING},
		[50]={CONST_SKILL_XUEYING},
		[60]={
						CONST_SKILL_MUYELIUXING,
						CONST_SKILL_BIHAICHAOSHENG
					}
	},
	[CONST_PARTY_GAIBANG+1] = {
		[10]={
						CONST_SKILL_GAIBANGZHANGFA,
						CONST_SKILL_GAIBANGBANGFA
					},
		[30]={
						CONST_SKILL_XIANGLONGZHANG,
						CONST_SKILL_DAGOUBANG
					},
		[40]={CONST_SKILL_HUABULIUSHOU},
		[50]={
						CONST_SKILL_KANGLONGYOUHUI,
						CONST_SKILL_BANGDAEGOU
					},
		[60]={CONST_SKILL_XIAOYAOGONG}
	},
	[CONST_PARTY_TIANREN+1] = {
		[10]={
						CONST_SKILL_TIANRENMAOFA,
						CONST_SKILL_TIANRENDAOFA,
						CONST_SKILL_HUOLIANFENHUA
					},
		[30]={		
						CONST_SKILL_LIEHONGQINGTIAN,
						CONST_SKILL_TUISHANTIANHAI,
						CONST_SKILL_FEIHONGWUJI
					},
		[40]={CONST_SKILL_BEISUQINGFENG},
		[50]={CONST_SKILL_LIMODUOPO},
		[60]={
						CONST_SKILL_TOUTIANHUANRI,
						CONST_SKILL_MOYANQISHA
					}
	},
	[CONST_PARTY_WUDANG+1] = {
		[10]={
						CONST_SKILL_WUDANGQUANFA,
						CONST_SKILL_WUDANGJIANFA
					},
		[30]={
						CONST_SKILL_BOJIERFU,
						ONST_SKILL_JIANFEIJINGTIAN
					},
		[40]={CONST_SKILL_TIYUNZONG},
		[50]={CONST_SKILL_ZUOWANGWUWO},
		[60]={CONST_SKILL_WUWOWUJIAN,CONST_SKILL_SANHUANTAOYUE}
	},
	[CONST_PARTY_KUNLUN+1] = {
		[10]={	
						CONST_SKILL_KUNLUNDAOFA,
						CONST_SKILL_KUNLUNJIANFA,
						CONST_SKILL_SHUFUZHOU,
						CONST_SKILL_QINGFENGFU
			},
		[30]={
						CONST_SKILL_YIQISANQING,
						CONST_SKILL_TIANJIXUNLEI,
						CONST_SKILL_BEIMINGDAOHAI,
						CONST_SKILL_TIANQINGDIZUO
					},
		[40]={
						CONST_SKILL_QIHANAOXUE,
						CONST_SKILL_QIXINFU
					},
		[50]={
						CONST_SKILL_KUANGFENGZHOUDIAN,
						CONST_SKILL_MIZONGHUANGYING
					},
		[60]={CONST_SKILL_WULEIZHENGFA}
	}
}
