--Trao gi¶i THDNB 13 - Created by DinhHQ - 20130618
Include("\\script\\vng_event\\traogiai\\npah\\vng_awardclass.lua")
Include("\\script\\vng_event\\traogiai\\npah\\vng_toolaward.lua")
tbCurSeason = tbAwardClass:New()
tbCurSeason.nStartDate = 201307180000
tbCurSeason.nEndDate = 201307212400
tbCurSeason.strName = "NhËn th­ëng trao gi¶i s©n ch¬i Vâ L©m"
tbCurSeason.strNPC = "ChiÕn T©m T«n Gi¶"
tbCurSeason.nID = 12
tbCurSeason.tbAccList = {
	["lifeofpie"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["nguyentram8888"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["milestone135"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["quanghuymario"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["ngamisangdaigia"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["lekimai165"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["usatvu"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["vietnamha2014"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["onehitodie"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["ngoctrungcdh"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["trucmai1007"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["boytapchoi2000"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["shenlong66o0o"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["thiennhansiuly"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["khongsaurang114"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["jerrymouse8888"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["mrnarga"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["ramphaikham06"]={{{ nAwardID = 1, nCount = 1},{ nAwardID = 2, nCount = 1},},},
	["bovt369"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},{ nAwardID = 9, nCount = 1},},},
	["vungtauvt2016"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["trungtitan"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["tuduc2006"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["nhocsun1201"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["laolangnguy895"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["muabandocui2"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["nhoxxlonely2"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["vungtauvt2015"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["cuuduong02"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},{ nAwardID = 9, nCount = 1},},},
	["laolangnguy893"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["ngodinhvu9739841"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},{ nAwardID = 4, nCount = 1},{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["cuuduong01"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["thedaicool"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["huynhduyman1991nt"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["mabu0o0"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},},},
	["danghung9998"]={{{ nAwardID = 2, nCount = 1},{ nAwardID = 3, nCount = 1},{ nAwardID = 4, nCount = 1},},},
	["myhanhmeo110"]={{{ nAwardID = 4, nCount = 1},{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["phanvanphu1984"]={{{ nAwardID = 4, nCount = 1},},},
	["khanhksc"]={{{ nAwardID = 4, nCount = 1},},},
	["phamhoangvuty"]={{{ nAwardID = 4, nCount = 1},},},
	["goodsave1"]={{{ nAwardID = 4, nCount = 1},},},
	["khanhthyx2010"]={{{ nAwardID = 4, nCount = 1},},},
	["langthangtimemtrongconmua"]={{{ nAwardID = 4, nCount = 1},},},
	["samac81"]={{{ nAwardID = 4, nCount = 1},},},
	["lanphuong1972"]={{{ nAwardID = 5, nCount = 1},},},
	["builanphuong118"]={{{ nAwardID = 5, nCount = 1},},},
	["luuthienthu007"]={{{ nAwardID = 5, nCount = 1},},},
	["allfriend92"]={{{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["duongchiminh"]={{{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["turnoff"]={{{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["quanglee33"]={{{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["dieternguyen01"]={{{ nAwardID = 6, nCount = 1000},{ nAwardID = 7, nCount = 5000},},},
	["utdeplam"]={{{ nAwardID = 8, nCount = 1},},},
	["madaogiangthe00"]={{{ nAwardID = 8, nCount = 1},},},
	["thanhbil110612"]={{{ nAwardID = 9, nCount = 1},},},
	["ngayhomdo112"]={{{ nAwardID = 9, nCount = 1},},},
	["tuanpro402"]={{{ nAwardID = 9, nCount = 1},},},
	["thanhbil11062012"]={{{ nAwardID = 9, nCount = 1},},},
	["vl9nam1kyniem"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu8o"]={{{ nAwardID = 9, nCount = 1},},},
	["tinaxinhdep84"]={{{ nAwardID = 9, nCount = 1},},},
	["yentangphong1551"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu7o7"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu9o1"]={{{ nAwardID = 9, nCount = 1},},},
	["gianghobahom2996"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu1oo"]={{{ nAwardID = 9, nCount = 1},},},
	["khaithienlapdia6969"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu7o4"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu4o1"]={{{ nAwardID = 9, nCount = 1},},},
	["quocyenak"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu7o1"]={{{ nAwardID = 9, nCount = 1},},},
	["motlanthoictag2"]={{{ nAwardID = 9, nCount = 1},},},
	["quocyenak5"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu6o1"]={{{ nAwardID = 9, nCount = 1},},},
	["langtu3o2"]={{{ nAwardID = 9, nCount = 1},},},
	["nhanghiquynhphuong270"]={{{ nAwardID = 9, nCount = 1},},},
	["ngamy270983"]={{{ nAwardID = 9, nCount = 1},},},
	["cuunguyet22"]={{{ nAwardID = 9, nCount = 1},},},
	["toans2quyen21"]={{{ nAwardID = 9, nCount = 1},},},
	["hieuoilnb"]={{{ nAwardID = 9, nCount = 1},},},
	["thuthaomylove50"]={{{ nAwardID = 9, nCount = 1},},},
	["volam9nam"]={{{ nAwardID = 9, nCount = 1},},},
	["ongte01"]={{{ nAwardID = 9, nCount = 1},},},
	["jerynguyen16111993"]={{{ nAwardID = 9, nCount = 1},},},
	["athinhnd86"]={{{ nAwardID = 9, nCount = 1},},},
	["ryuoden01"]={{{ nAwardID = 9, nCount = 1},},},
	["truonglanh995"]={{{ nAwardID = 9, nCount = 1},},},
	["tienthaolotrung"]={{{ nAwardID = 9, nCount = 1},},},
	["hathienthu899"]={{{ nAwardID = 9, nCount = 1},},},
	["cuunguyet0001"]={{{ nAwardID = 9, nCount = 1},},},
	["blackcat90"]={{{ nAwardID = 9, nCount = 1},},},
	["donglvph02312 "]={{{ nAwardID = 9, nCount = 1},},},
	["levanmen992"]={{{ nAwardID = 9, nCount = 1},},},
	["thientuchinhnhan1"]={{{ nAwardID = 9, nCount = 1},},},
	["vltknldk01"]={{{ nAwardID = 9, nCount = 1},},},
	["nguoinaodo200"]={{{ nAwardID = 9, nCount = 1},},},
	["ngayhomdo012"]={{{ nAwardID = 9, nCount = 1},},},
	["tamtieuthu88"]={{{ nAwardID = 9, nCount = 1},},},
	["vuongtinh1212"]={{{ nAwardID = 9, nCount = 1},},},
	["vanphuocbds"]={{{ nAwardID = 9, nCount = 1},},},
	["1thoidenho20010"]={{{ nAwardID = 9, nCount = 1},},},
	["heoconbungbuhihi"]={{{ nAwardID = 9, nCount = 1},},},
	["loadingsmileo1991"]={{{ nAwardID = 9, nCount = 1},},},
	["quangvu270890"]={{{ nAwardID = 9, nCount = 1},},},
	["langtutieudao8"]={{{ nAwardID = 9, nCount = 1},},},
	["benopro01"]={{{ nAwardID = 9, nCount = 1},},},
	["hunp110222"]={{{ nAwardID = 9, nCount = 1},},},
	["hunp11022"]={{{ nAwardID = 9, nCount = 1},},},
	["lethikieungaluukyphong1"]={{{ nAwardID = 9, nCount = 1},},},
	["deghe2013"]={{{ nAwardID = 9, nCount = 1},},},
	[" nguyennhatdat2"]={{{ nAwardID = 9, nCount = 1},},},
	["cuuduongcuunien"]={{{ nAwardID = 9, nCount = 1},},},
	["xomraumuong123"]={{{ nAwardID = 9, nCount = 1},},},
	["nobody2086"]={{{ nAwardID = 9, nCount = 1},},},
	["bemapbn92"]={{{ nAwardID = 9, nCount = 1},},},
	["nobody20852"]={{{ nAwardID = 9, nCount = 1},},},
	["gucciboy1"]={{{ nAwardID = 9, nCount = 1},},},
	["chutieu17"]={{{ nAwardID = 9, nCount = 1},},},
	["elvisdung2"]={{{ nAwardID = 9, nCount = 1},},},
	["nguyenngohaan11020"]={{{ nAwardID = 9, nCount = 1},},},
	[" backspacety02"]={{{ nAwardID = 9, nCount = 1},},},
	["anhsaomuadong2014"]={{{ nAwardID = 9, nCount = 1},},},
	["bachbophikiem1100"]={{{ nAwardID = 9, nCount = 1},},},
	["lamniemtu31"]={{{ nAwardID = 9, nCount = 1},},},
	["phongbcc96"]={{{ nAwardID = 9, nCount = 1},},},
	["antkstehgice"]={{{ nAwardID = 9, nCount = 1},},},
	["doquyentran2012"]={{{ nAwardID = 9, nCount = 1},},},
	["datbeo000002"]={{{ nAwardID = 9, nCount = 1},},},
	["nikdmon"]={{{ nAwardID = 9, nCount = 1},},},
	["nhttkm001"]={{{ nAwardID = 9, nCount = 1},},},
	["caoanh8788"]={{{ nAwardID = 9, nCount = 1},},},
	["fantacocacola1"]={{{ nAwardID = 9, nCount = 1},},},
	["vinhtoan208"]={{{ nAwardID = 9, nCount = 1},},},
	["silvergold011062013"]={{{ nAwardID = 9, nCount = 1},},},
	["kenxd65"]={{{ nAwardID = 9, nCount = 1},},},
	["kenxd13"]={{{ nAwardID = 9, nCount = 1},},},
	["91dragonc"]={{{ nAwardID = 9, nCount = 1},},},
	["haokiettrung5"]={{{ nAwardID = 9, nCount = 1},},},
	["nuidofclol12345"]={{{ nAwardID = 9, nCount = 1},},},
	["tungboing26091989"]={{{ nAwardID = 9, nCount = 1},},},
	["tungboing260919890"]={{{ nAwardID = 9, nCount = 1},},},
	["bdsonghiep"]={{{ nAwardID = 9, nCount = 1},},},
	["volove0001"]={{{ nAwardID = 9, nCount = 1},},},
	["anrauma1993"]={{{ nAwardID = 9, nCount = 1},},},
	["vtoandong"]={{{ nAwardID = 9, nCount = 1},},},
	["gameclubdbp1"]={{{ nAwardID = 9, nCount = 1},},},
	["gameclubdbp2"]={{{ nAwardID = 9, nCount = 1},},},
	["aaatila33333"]={{{ nAwardID = 9, nCount = 1},},},
	["romanxg222"]={{{ nAwardID = 9, nCount = 1},},},
	["kojirono09"]={{{ nAwardID = 9, nCount = 1},},},
	["dinhthanh336"]={{{ nAwardID = 9, nCount = 1},},},
	["cuude0001"]={{{ nAwardID = 9, nCount = 1},},},
	["vothienk19"]={{{ nAwardID = 9, nCount = 1},},},
	["cuogkuto"]={{{ nAwardID = 9, nCount = 1},},},
	["trandung001188"]={{{ nAwardID = 9, nCount = 1},},},
	["xuanliem2100"]={{{ nAwardID = 9, nCount = 1},},},
	["cogachet01"]={{{ nAwardID = 9, nCount = 1},},},
	["ngochoatran2013"]={{{ nAwardID = 9, nCount = 1},},},
	[" thieulamcuude"]={{{ nAwardID = 9, nCount = 1},},},
	["cuudeaz"]={{{ nAwardID = 9, nCount = 1},},},
	["vn2468897tn2"]={{{ nAwardID = 9, nCount = 1},},},
	["baolong19901"]={{{ nAwardID = 9, nCount = 1},},},
	["phuockt1005"]={{{ nAwardID = 9, nCount = 1},},},
	["bloodqueenvn18"]={{{ nAwardID = 9, nCount = 1},},},
	["cntpthanhlap2802a"]={{{ nAwardID = 9, nCount = 1},},},
	["kkdn233"]={{{ nAwardID = 9, nCount = 1},},},
	["kkdn232"]={{{ nAwardID = 9, nCount = 1},},},
	["lekhuongduy2008"]={{{ nAwardID = 9, nCount = 1},},},
	["lamlovepe01"]={{{ nAwardID = 9, nCount = 1},},},
	["vlcmcti"]={{{ nAwardID = 9, nCount = 1},},},
	["bjcafe90"]={{{ nAwardID = 9, nCount = 1},},},
	["dkny2561993."]={{{ nAwardID = 9, nCount = 1},},},
	["anhyen2504"]={{{ nAwardID = 9, nCount = 1},},},
	["kietcuibap2013"]={{{ nAwardID = 9, nCount = 1},},},
	["haovuktsdmn1"]={{{ nAwardID = 9, nCount = 1},},},
	["khathanhthieulam"]={{{ nAwardID = 9, nCount = 1},},},
	["onhuutho21"]={{{ nAwardID = 9, nCount = 1},},},
	["dinhhongcd"]={{{ nAwardID = 9, nCount = 1},},},
	["anhnamtronno00"]={{{ nAwardID = 9, nCount = 1},},},
	["svcuude6"]={{{ nAwardID = 9, nCount = 1},},},
	["svcuude7"]={{{ nAwardID = 9, nCount = 1},},},
	["ngoanhtuan30x"]={{{ nAwardID = 9, nCount = 1},},},
	["nghiaso000000000"]={{{ nAwardID = 9, nCount = 1},},},
	["ngoanhtuan21x"]={{{ nAwardID = 9, nCount = 1},},},
	["luongiagvl1986"]={{{ nAwardID = 9, nCount = 1},},},
	["nguyenthanhthuyet194"]={{{ nAwardID = 9, nCount = 1},},},
	["duongpin1107"]={{{ nAwardID = 9, nCount = 1},},},
	["c0ng3lo90"]={{{ nAwardID = 9, nCount = 1},},},
	["ngudocshitun12"]={{{ nAwardID = 9, nCount = 1},},},
	["truongshines3"]={{{ nAwardID = 9, nCount = 1},},},
	["ngarecuocdoi8692"]={{{ nAwardID = 9, nCount = 1},},},
	["ngayayvabaygio06"]={{{ nAwardID = 9, nCount = 1},},},
	["suxinh9999"]={{{ nAwardID = 9, nCount = 1},},},
	["quansailor"]={{{ nAwardID = 9, nCount = 1},},},
	["nh0xstupid17x"]={{{ nAwardID = 9, nCount = 1},},},
	["phuockt1013"]={{{ nAwardID = 9, nCount = 1},},},
	["chorongnm2014"]={{{ nAwardID = 9, nCount = 1},},},
	["nethoanglongld01"]={{{ nAwardID = 9, nCount = 1},},},
	["superfox668"]={{{ nAwardID = 9, nCount = 1},},},
	["khoinghiep0009"]={{{ nAwardID = 9, nCount = 1},},},
	["shenno13"]={{{ nAwardID = 9, nCount = 1},},},
	["getlucky01"]={{{ nAwardID = 9, nCount = 1},},},
	["bxkforever12"]={{{ nAwardID = 9, nCount = 1},},},
	["baccaihoaninh"]={{{ nAwardID = 9, nCount = 1},},},
	["baccaihoaninh2"]={{{ nAwardID = 9, nCount = 1},},},
	["baccaihoaninh4"]={{{ nAwardID = 9, nCount = 1},},},
	["hungbjn90"]={{{ nAwardID = 9, nCount = 1},},},
	["myfriendbacninh1015"]={{{ nAwardID = 9, nCount = 1},},},
	["nkhti11kt1"]={{{ nAwardID = 9, nCount = 1},},},
	["nguyen01888009888"]={{{ nAwardID = 9, nCount = 1},},},
	["changkieuvl01"]={{{ nAwardID = 9, nCount = 1},},},
	["viloveak22"]={{{ nAwardID = 9, nCount = 1},},},
	["hungbjn89"]={{{ nAwardID = 9, nCount = 1},},},
	["mobiistarbean454"]={{{ nAwardID = 9, nCount = 1},},},
	["adonglangtu"]={{{ nAwardID = 9, nCount = 1},},},
	["bediemgl1991"]={{{ nAwardID = 9, nCount = 1},},},
	["chienvuong1092"]={{{ nAwardID = 9, nCount = 1},},},
	["coembendoibmt1"]={{{ nAwardID = 9, nCount = 1},},},
	["lamkhung13071"]={{{ nAwardID = 9, nCount = 1},},},
	["vuthuanbv0005"]={{{ nAwardID = 9, nCount = 1},},},
	["zombie3332"]={{{ nAwardID = 9, nCount = 1},},},
	["laichaus10"]={{{ nAwardID = 9, nCount = 1},},},
	["phuongnetkg1000"]={{{ nAwardID = 9, nCount = 1},},},
	["chunseven02"]={{{ nAwardID = 9, nCount = 1},},},
	["conlondao1462013"]={{{ nAwardID = 9, nCount = 1},},},
	["thuonglang24079"]={{{ nAwardID = 9, nCount = 1},},},
	["thuonglang24075"]={{{ nAwardID = 9, nCount = 1},},},
	["thuonglang24076"]={{{ nAwardID = 9, nCount = 1},},},
	["thuonglang240711"]={{{ nAwardID = 9, nCount = 1},},},
	["choilai8705"]={{{ nAwardID = 9, nCount = 1},},},
	["quanhung15686"]={{{ nAwardID = 9, nCount = 1},},},
	["thjenhung87"]={{{ nAwardID = 9, nCount = 1},},},
	["xe24076"]={{{ nAwardID = 9, nCount = 1},},},
	["thjennhan8x4"]={{{ nAwardID = 9, nCount = 1},},},
	["thjennhan8x5"]={{{ nAwardID = 9, nCount = 1},},},
	["thjennhan8x6"]={{{ nAwardID = 9, nCount = 1},},},
	["oneluv4u0202"]={{{ nAwardID = 9, nCount = 1},},},
	["nguyenhongnguyen9999"]={{{ nAwardID = 9, nCount = 1},},},
	["mrquandbp"]={{{ nAwardID = 9, nCount = 1},},},
	["atomicbomb84"]={{{ nAwardID = 9, nCount = 1},},},
	["11ktti2"]={{{ nAwardID = 9, nCount = 1},},},
	["tranminhhp90"]={{{ nAwardID = 9, nCount = 1},},},
	["chomthienlongbac"]={{{ nAwardID = 10, nCount = 1},},},
	["odin12121991"]={{{ nAwardID = 10, nCount = 1},},},
	["vihantaisinh10"]={{{ nAwardID = 10, nCount = 1},},},
	["eros2501071"]={{{ nAwardID = 10, nCount = 1},},},
	["blue206"]={{{ nAwardID = 10, nCount = 1},},},
	["bachduong010493"]={{{ nAwardID = 10, nCount = 1},},},
	["boom288"]={{{ nAwardID = 10, nCount = 1},},},
	["gamekhu86"]={{{ nAwardID = 10, nCount = 1},},},
	["ngubathienha0160"]={{{ nAwardID = 10, nCount = 1},},},
	["thiennhancuibap7893"]={{{ nAwardID = 10, nCount = 1},},},
	["tram19391"]={{{ nAwardID = 10, nCount = 1},},},
	["heomoi2110"]={{{ nAwardID = 10, nCount = 1},},},
	["class9b"]={{{ nAwardID = 10, nCount = 1},},},
	["vosonglenh100vn"]={{{ nAwardID = 10, nCount = 1},},},
}
tbCurSeason.tbPrizeList = {			
	[1]={szName="Hçn nguyªn ch©n ®¬n",tbProp={6,1,30301,1,0,0},nCount=1,nExpiredTime=43200},
	[2]={szName="MÆt n¹ - Anh hïng chiÕn tr­êng",tbProp={0,11,482,1,0,0},nCount=1,nExpiredTime=43200},
	[3]={szName="[Kh«ng thÓ gia h¹n] Long §¶m",tbProp={0,4485},nCount=1,nQuality = 1,nExpiredTime=43200,},
	[4]={szName="Phi phong Ngù Phong (X¸c suÊt hãa gi¶i s¸t th­¬ng)",tbProp={0,3474},nCount=1,nQuality = 1,nBindState=-2,nExpiredTime=43200,},
	[5]={szName="XÝch L©n Kim Kh¶i - Tù chän hÖ ph¸i",tbProp={6,1,30386,1,0,0},nCount=1,tbParam={6,0,0,0,0,0}},
	[6]={szName="Ch©n Nguyªn §¬n (trung)",tbProp={6,1,30228,1,0,0},nCount=1,nBindState=-2},
	[7]={szName="Hé M¹ch §¬n",tbProp={6,1,3203,1,0,0},nCount=1,nBindState=-2},
	[8]={szName="Hång bao An khang",tbProp={6,1,2105,1,0,0},nCount=1},
	[9]={szName="Cµn Kh«n Song TuyÖt Béi",tbProp={6,1,2219,1,0,0},nCount=1,nBindState=-2,nExpiredTime=43200},
	[10]={szName="Phi phong Kinh L«i (X¸c suÊt hãa gi¶i s¸t th­¬ng)",tbProp={0,3471},nCount=1,nQuality = 1,nBindState=-2,nExpiredTime=43200,},
}

tbCurSeason.tbExtPointBit = {	
	[1] = {nID = 3, nBit = 3, nVer = 2},
}
tbCurSeason.nFreeCellRequire  = 20
tbCurSeason.tbLog = {"TraoThuongSanChoiVL", "NhanThuongTaiChienTamTonGia"}
if tbCurSeason:IsOver() == 1 then
	tbCurSeason = nil
else
	tbVngToolAward:AddSeason(tbCurSeason)
end