-- ÎÄ¼þÃû¡¡£ºtaskhead.lua
-- ´´½¨Õß¡¡£ºzhongchaolong
-- ´´½¨Ê±¼ä£º2008-01-19 15:05:24


Include("\\script\\event\\springfestival08\\allbrother\\head.lua")


Include("\\script\\event\\springfestival08\\allbrother\\itemlist.lua")

allbrother_0801_tbTaskList = 
{
	--ÕÒnpcÈÎÎñ	
	[1] = {nTaskType = 1, szShow = "Vµo ThÇn Tiªn §éng tÇm Cao l·o nh©n."},
	[2] = {nTaskType = 1, szShow = "§Õn Tr­êng Giang Nguyªn §Çu tÇm Giíi ®¹i hiÖp."},
	[3] = {nTaskType = 1, szShow = "§Õn L©m An tÇm Tr­¬ng t­íng qu©n."},
	[4] = {nTaskType = 1, szShow = "§Õn Ngò §éc Gi¸o thØnh gi¸o anh chµng mÆt ®en."},
	[5] = {nTaskType = 1, szShow = "D¹o ch¬i B¸ch Hoa §×nh t×m ng­êi ­ng ý."},
	[6] = {nTaskType = 1, szShow = "Th­îng C«n Lu©n ph¸i t×m ng­êi hä Kh©u."},
	[7] = {nTaskType = 1, szShow = "§Õn Thanh Thµnh S¬n t×m chµng hä C¶nh."},
	[8] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n tÇm tr¸ng sÜ."},
	[9] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n tÇm tr¸ng sÜ."},
	[10] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n tÇm tr¸ng sÜ."},
	[11] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n tÇm tr¸ng sÜ."},
	[12] = {nTaskType = 1, szShow = "§¨ng Vâ §ang S¬n tÇm chµng hä DiÖp."},
	[13] = {nTaskType = 1, szShow = "Vµo Kª Qu¸n ®éng hái th¨m nµng Êy."},
	[14] = {nTaskType = 1, szShow = "Qua §¹i Lý t×m chµng t­¬ng t­."},
	--ÕÒÎïÆ·
	[15] = {nTaskType = 0, szShow = "Thu thËp Long Tiªn H­¬ng Nang hÖ Méc, L­u Tiªn QuÇn hÖ Kim.", tbList = {allbrother_0801_tbItemList[1], allbrother_0801_tbItemList[16]			}},
	[16] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch Giíi ChØ hÖ Thñy, Tr©n Ch©u H¹ng Liªn hÖ méc.", tbList = {allbrother_0801_tbItemList[2],	allbrother_0801_tbItemList[17]			}},
	[17] = {nTaskType = 0, szShow = "Thu thËp Gi¸c H¶i Bæng hÖ Kim, Thiªn T»m Ngoa hÖ Thæ.", tbList = {allbrother_0801_tbItemList[3],	allbrother_0801_tbItemList[18]				}},
	[18] = {nTaskType = 0, szShow = "Thu thËp TuyÒn Long bµo hÖ Háa, Du¬ng ChØ B¹ch Ngäc hÖ Thñy.", tbList = {allbrother_0801_tbItemList[4],	allbrother_0801_tbItemList[19]			}},
	[19] = {nTaskType = 0, szShow = "T×m ngùa Tóc Su¬ng, Phi Phông Ngoa hÖ Háa.", tbList = {allbrother_0801_tbItemList[5],	allbrother_0801_tbItemList[20]						}},
	[20] = {nTaskType = 0, szShow = "Thu thËp Toµn NghÖ Gi¸p hÖ Thñy, HuyÒn ThiÕt KiÕm hÖ Thñy.", tbList = {allbrother_0801_tbItemList[6],	allbrother_0801_tbItemList[21]				}},
	[21] = {nTaskType = 0, szShow = "Thu thËp Long L©n Yªu §¸i hÖ Kim, ThiÕt Trñy thñ hÖ Thæ", tbList = {allbrother_0801_tbItemList[7],	allbrother_0801_tbItemList[22]			}},
	[22] = {nTaskType = 0, szShow = "Thu thËp Yªu §ao hÖ Háa, Ng­ L¹p hÖ Kim.", tbList = {allbrother_0801_tbItemList[8],	allbrother_0801_tbItemList[23]					}},
	[23] = {nTaskType = 0, szShow = "Thu thËp Phông vÜ quÇn - hÖ háa, Tö phØ thóy hé th©n phï - hÖ kim", tbList = {allbrother_0801_tbItemList[9],	allbrother_0801_tbItemList[24]			}},
	[24] = {nTaskType = 0, szShow = "Thu thËp Háa NhuÖ Thu¬ng hÖ Méc, Kim Phông TriÓn SÜ hÖ Méc.", tbList = {allbrother_0801_tbItemList[10],	allbrother_0801_tbItemList[25]			}},
	[25] = {nTaskType = 0, szShow = "Thu thËp Thanh §ång N÷ gi¸p hÖ Méc, Ph¸ Thiªn KÝch hÖ Kim.", tbList = {allbrother_0801_tbItemList[11],	allbrother_0801_tbItemList[26]			}},
	[26] = {nTaskType = 0, szShow = "Thu thËp ThÊt B¶o cµ sa hÖ Thñy, B¨ng Ph¸ch Hµn Ngäc Tr¹c hÖ Háa.", tbList = {allbrother_0801_tbItemList[12],	allbrother_0801_tbItemList[27]		}},
	[27] = {nTaskType = 0, szShow = "Thu thËp Kim Yªu §¸i hÖ Thæ, Phi Phông Ngoa hÖ Thæ.", tbList = {allbrother_0801_tbItemList[13],	allbrother_0801_tbItemList[28]		}},
	[28] = {nTaskType = 0, szShow = "Thu thËp Tr©n Ch©u H¹ng Liªn hÖ Ho¶, B¹ch PhØ Thóy Hé Th©n Phï hÖ Méc.", tbList = {allbrother_0801_tbItemList[14],	allbrother_0801_tbItemList[29]	}},
	[29] = {nTaskType = 0, szShow = "Thu thËp H¶i Lam B¶o Th¹ch Giíi ChØ hÖ Kim, ngùa §¹i UyÓn B¹ch M·.", tbList = {allbrother_0801_tbItemList[15],	allbrother_0801_tbItemList[30]			}},
	[30] = {nTaskType = 0, szShow = "Thu thËp Thiªn NhÉn MËt Trang hÖ Háa", tbList = {allbrother_0801_tbItemList[31]}},
	[31] = {nTaskType = 0, szShow = "Thu thËp ngùa Tóc S­¬ng", tbList = {allbrother_0801_tbItemList[5]}},
	[32] = {nTaskType = 0, szShow = "Thu thËp Kim Lò hµi hÖ Kim", tbList = {allbrother_0801_tbItemList[32]}},
	[33] = {nTaskType = 0, szShow = "Thu thËp §¹i Phong §ao hÖ Méc", tbList = {allbrother_0801_tbItemList[33]}},
	[34] = {nTaskType = 0, szShow = "Thu thËp HuyÒn ThiÕt KiÕm hÖ Thæ", tbList = {allbrother_0801_tbItemList[34]}},
	[35] = {nTaskType = 0, szShow = "Thu thËp Cöu TiÕt Xu¬ng VÜ Ngoa hÖ Thñy", tbList = {allbrother_0801_tbItemList[35]}},
	[36] = {nTaskType = 0, szShow = "Thu thËp Thiªn T»m Hé UyÓn hÖ Thæ", tbList = {allbrother_0801_tbItemList[36]}},
	[37] = {nTaskType = 0, szShow = "Thu thËp Thiªn T»m Yªu §¸i hÖ Thæ", tbList = {allbrother_0801_tbItemList[37]}},
	[38] = {nTaskType = 0, szShow = "Thu thËp TrÇm Hu¬ng sam hÖ Háa", tbList = {allbrother_0801_tbItemList[38]}},
	[39] = {nTaskType = 0, szShow = "Thu thËp TuyÒn Long bµo hÖ Méc", tbList = {allbrother_0801_tbItemList[39]}},
	[40] = {nTaskType = 0, szShow = "Thu thËp ¤ TÇm M·o hÖ Méc", tbList = {allbrother_0801_tbItemList[40]}},
	[41] = {nTaskType = 0, szShow = "Thu thËp Khæng Tuíc Linh hÖ Méc", tbList = {allbrother_0801_tbItemList[41]}},
	[42] = {nTaskType = 0, szShow = "Thu thËp Long Phông HuyÕt Ngäc Tr¹c hÖ Thæ", tbList = {allbrother_0801_tbItemList[42]}},
	[43] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch Giíi ChØ hÖ Kim", tbList = {allbrother_0801_tbItemList[43]}},
	[44] = {nTaskType = 0, szShow = "Thu thËp Lôc PhØ Thóy Hé Th©n phï hÖ Kim", tbList = {allbrother_0801_tbItemList[44]}},
	[45] = {nTaskType = 0, szShow = "Thu thËp D­¬ng ChØ B¹ch Ngäc hÖ Thñy.", tbList = {allbrother_0801_tbItemList[19]}},
	[46] = {nTaskType = 0, szShow = "Thu thËp ¢m Du¬ng V« Cùc qu¸n hÖ Háa", tbList = {allbrother_0801_tbItemList[45]}},
	[47] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch H¹ng Liªn hÖ Thñy", tbList = {allbrother_0801_tbItemList[46]}},
	[48] = {nTaskType = 0, szShow = "Thu thËp Long Tiªn Hu¬ng Nang hÖ Thæ", tbList = {allbrother_0801_tbItemList[47]}},
	[49] = {nTaskType = 0, szShow = "Thu thËp Ph¸ Thiªn chïy hÖ Kim", tbList = {allbrother_0801_tbItemList[48]}},
	[50] = {nTaskType = 0, szShow = "Thu thËp ®å phæ hoµng kim - §Þnh Quèc Thanh Sa Tr­êng Sam", tbList = {allbrother_0801_tbItemList[49]} },
	[51] = {nTaskType = 0, szShow = "Thu thËp ®å phæ hoµng kim - §Þnh Quèc Ng©n Tµm Yªu ®¸i", tbList = {allbrother_0801_tbItemList[50]} },
	[52] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc ¤ Sa Ph¸t Qu¸n", tbList = {allbrother_0801_tbItemList[51]} },
	[53] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc XÝch Quyªn NhuyÔn Ngoa", tbList = {allbrother_0801_tbItemList[52]} },
	[54] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc Tö §»ng Hé UyÓn", tbList = {allbrother_0801_tbItemList[53]} },
	[55] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - Méng Long Kim Ti ChÝnh Hång Cµ Sa", tbList = {allbrother_0801_tbItemList[54]} },
	[56] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - Chó Ph­îc DiÖt L«i C¶nh Phï", tbList = {allbrother_0801_tbItemList[55]} },
	[57] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - U Lung MÆc Thï NhuyÔn Lý", tbList = {allbrother_0801_tbItemList[56]} },
	[58] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þa Ph¸ch H¾c DiÖm Xung Thiªn Liªn", tbList = {allbrother_0801_tbItemList[57]} },
	[59] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - BÝch H¶i Uyªn ¦¬ng Liªn Hoµn §ao", tbList = {allbrother_0801_tbItemList[58]} },
	[60] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - V« TrÇn Thanh T©m H­íng ThiÖn Ch©u", tbList = {allbrother_0801_tbItemList[59]} },
	[61] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 1", tbList = {allbrother_0801_tbItemList[60]} },
	[62] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 2", tbList = {allbrother_0801_tbItemList[61]} },
	[63] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 3", tbList = {allbrother_0801_tbItemList[62]} },
	[64] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 4", tbList = {allbrother_0801_tbItemList[63]} },
	[65] = {nTaskType = 0, szShow = "Thu thËp Kh¸ng ®¬n chi gi¸c", tbList = {allbrother_0801_tbItemList[64]} },
	[66] = {nTaskType = 0, szShow = "Thu thËp SÜ binh chi hiÖu gi¸c", tbList = {allbrother_0801_tbItemList[65]} },
	[67] = {nTaskType = 0, szShow = "Thu thËp Bå c©u", tbList = {allbrother_0801_tbItemList[66]} },
	[68] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i ®éc hoµn", tbList = {allbrother_0801_tbItemList[67]} },
	[69] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i b¨ng hoµn", tbList = {allbrother_0801_tbItemList[68]} },
	[70] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i phæ hoµn", tbList = {allbrother_0801_tbItemList[69]} },
	[71] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi b¨ng hoµn", tbList = {allbrother_0801_tbItemList[70]} },
	[72] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi phæ hoµn", tbList = {allbrother_0801_tbItemList[71]} },
	[73] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi ®éc hoµn", tbList = {allbrother_0801_tbItemList[72]} },
	[74] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi l«i hoµn", tbList = {allbrother_0801_tbItemList[73]} },
	[75] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi háa hoµn", tbList = {allbrother_0801_tbItemList[74]} },
	[76] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim tr­êng mÖnh hoµn", tbList = {allbrother_0801_tbItemList[75]} },
	[77] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim gia bµo hoµn", tbList = {allbrother_0801_tbItemList[76]} },
	[78] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim cao thiÓm hoµn", tbList = {allbrother_0801_tbItemList[77]} },
	[79] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim cao trung hoµn", tbList = {allbrother_0801_tbItemList[78]} },
	[80] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim phi tèc hoµn", tbList = {allbrother_0801_tbItemList[79]} },
	[81] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim phæ phßng hoµn", tbList = {allbrother_0801_tbItemList[80]} },
	[82] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim b¨ng phßng hoµn", tbList = {allbrother_0801_tbItemList[81]} },
	[83] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim l«i phßng hoµn", tbList = {allbrother_0801_tbItemList[82]} },
	[84] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim háa phßng hoµn", tbList = {allbrother_0801_tbItemList[83]} },
	[85] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ®éc phßng hoµn", tbList = {allbrother_0801_tbItemList[84]} },
	[86] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (tiÓu)", tbList = {allbrother_0801_tbItemList[85]} },
	[87] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (trung)", tbList = {allbrother_0801_tbItemList[86]} },
	[88] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (®¹i)", tbList = {allbrother_0801_tbItemList[87]} },
	[89] = {nTaskType = 0, szShow = "Thu thËp ChiÕn cæ", tbList = {allbrother_0801_tbItemList[88]} },
	[90] = {nTaskType = 0, szShow = "Thu thËp LÖnh bµi", tbList = {allbrother_0801_tbItemList[89]} },
	[91] = {nTaskType = 0, szShow = "Thu thËp 10 huyÒn tinh kho¸ng th¹ch (cÊp 1)", tbList = {allbrother_0801_tbItemList[90]} },
	[92] = {nTaskType = 0, szShow = "Thu thËp 10 huyÒn tinh kho¸ng th¹ch (cÊp 2)", tbList = {allbrother_0801_tbItemList[91]} },
	[93] = {nTaskType = 0, szShow = "Thu thËp 5 huyÒn tinh kho¸ng th¹ch (cÊp 3)", tbList = {allbrother_0801_tbItemList[92]} },
	[94] = {nTaskType = 0, szShow = "Thu thËp 1 huyÒn tinh kho¸ng th¹ch (cÊp 4)", tbList = {allbrother_0801_tbItemList[93]} },
	[95] = {nTaskType = 0, szShow = "Thu thËp ThÝ gi¶ chi Ên", tbList = {allbrother_0801_tbItemList[94]} },
	[96] = {nTaskType = 0, szShow = "Thu thËp 20 Khiªu chiÕn lÖnh", tbList = {allbrother_0801_tbItemList[95]} },
	[97] = {nTaskType = 0, szShow = "Thu thËp 2 Thiªn s¬n b¶o lé", tbList = {allbrother_0801_tbItemList[96]} },
	[98] = {nTaskType = 0, szShow = "Thu thËp B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[97]} },
	[99] = {nTaskType = 0, szShow = "Thu thËp lÖnh bµi Phong L¨ng §é", tbList = {allbrother_0801_tbItemList[98]} },
	[100] = {nTaskType = 0, szShow = "Thu thËp HiÖp cèt chi ®an t©m giíi", tbList = {allbrother_0801_tbItemList[99]} },
	[101] = {nTaskType = 0, szShow = "Thu thËp HiÖp cèt ®a t×nh hoµn", tbList = {allbrother_0801_tbItemList[100]} },
	[102] = {nTaskType = 0, szShow = "Thu thËp Nhu t×nh phông nghi giíi chØ", tbList = {allbrother_0801_tbItemList[101]} },
	[103] = {nTaskType = 0, szShow = "Thu thËp Nhu t×nh thôc n÷ h¹ng liªn", tbList = {allbrother_0801_tbItemList[102]} },
	[104] = {nTaskType = 0, szShow = "Thu thËp §Þnh quèc tö ®»ng hé uyÓn", tbList = {allbrother_0801_tbItemList[103]} },
	[105] = {nTaskType = 0, szShow = "Thu thËp §Þnh quèc ng©n tµm yªu ®¸i", tbList = {allbrother_0801_tbItemList[104]} },
	[106] = {nTaskType = 0, szShow = "Thu thËp HuyÒn thiÕt kho¸ng", tbList = {allbrother_0801_tbItemList[105]} },
	[107] = {nTaskType = 0, szShow = "Thu thËp Khæng t­íc th¹ch", tbList = {allbrother_0801_tbItemList[106]} },
	[108] = {nTaskType = 0, szShow = "Thu thËp MËt ng©n kho¸ng", tbList = {allbrother_0801_tbItemList[107]} },
	[109] = {nTaskType = 0, szShow = "Thu thËp Phï dung th¹ch", tbList = {allbrother_0801_tbItemList[108]} },
	[110] = {nTaskType = 0, szShow = "Thu thËp Chu sa th¹ch", tbList = {allbrother_0801_tbItemList[109]} },
	[111] = {nTaskType = 0, szShow = "Thu thËp Chung nhò th¹ch", tbList = {allbrother_0801_tbItemList[110]} },
	[112] = {nTaskType = 0, szShow = "Thu thËp ThiÕt la h¸n", tbList = {allbrother_0801_tbItemList[111]} },
	[113] = {nTaskType = 0, szShow = "Thu thËp Bµn nh­îc t©m kinh", tbList = {allbrother_0801_tbItemList[112]} },
	[114] = {nTaskType = 0, szShow = "Thu thËp DiÖt kiÕm mËt tÞch", tbList = {allbrother_0801_tbItemList[113]} },
	[115] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn ®ao ph¸p", tbList = {allbrother_0801_tbItemList[114]} },
	[116] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn song ®ao", tbList = {allbrother_0801_tbItemList[115]} },
	[117] = {nTaskType = 0, szShow = "Thu thËp C¸i bang ch­ëng ph¸p", tbList = {allbrother_0801_tbItemList[116]} },
	[118] = {nTaskType = 0, szShow = "Thu thËp C¸i bang c«n ph¸p", tbList = {allbrother_0801_tbItemList[117]} },
	[119] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng chïy ph¸p quyÓn 1", tbList = {allbrother_0801_tbItemList[118]} },
	[120] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng th­¬ng ph¸p quyÓn 2", tbList = {allbrother_0801_tbItemList[119]} },
	[121] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng ®ao ph¸p quyÓn 3", tbList = {allbrother_0801_tbItemList[120]} },
	[122] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m quyÒn ph¸p quyÓn 1", tbList = {allbrother_0801_tbItemList[121]} },
	[123] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m c«n ph¸p quyÓn 2", tbList = {allbrother_0801_tbItemList[122]} },
	[124] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m ®ao ph¸p quyÓn 3", tbList = {allbrother_0801_tbItemList[123]} },
	[125] = {nTaskType = 0, szShow = "Thu thËp Phi ®ao thuËt (NhiÕp hån nguyÖt ¶nh)", tbList = {allbrother_0801_tbItemList[124]} },
	[126] = {nTaskType = 0, szShow = "Thu thËp Phi tiªu thuËt (Cöu cung phi tinh)", tbList = {allbrother_0801_tbItemList[125]} },
	[127] = {nTaskType = 0, szShow = "Thu thËp Tô tiÔn ThuËt (B¹o Vò Lª Hoa)", tbList = {allbrother_0801_tbItemList[126]} },
	[128] = {nTaskType = 0, szShow = "Thu thËp H·m TÜnh ThuËt (Lo¹n Hoµn KÝch)", tbList = {allbrother_0801_tbItemList[127]} },
	[129] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc ch­ëng ph¸p quyÓn 1", tbList = {allbrother_0801_tbItemList[128]} },
	[130] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc ®ao ph¸p quyÓn 2", tbList = {allbrother_0801_tbItemList[129]} },
	[131] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc nhiÕp t©m thuËt quyÓn 3", tbList = {allbrother_0801_tbItemList[130]} },
	[132] = {nTaskType = 0, szShow = "Thu thËp DiÖt kiÕm mËt tÞch", tbList = {allbrother_0801_tbItemList[131]} },
	[133] = {nTaskType = 0, szShow = "Thu thËp Nga My phËt quang ch­ëng mËt tÞch", tbList = {allbrother_0801_tbItemList[132]} },
	[134] = {nTaskType = 0, szShow = "Thu thËp phæ ®é mËt tÞch", tbList = {allbrother_0801_tbItemList[133]} },
	[135] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn ®ao ph¸p", tbList = {allbrother_0801_tbItemList[134]} },
	[136] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn song ®ao", tbList = {allbrother_0801_tbItemList[135]} },
	[137] = {nTaskType = 0, szShow = "Thu thËp C¸i bang ch­ëng ph¸p", tbList = {allbrother_0801_tbItemList[136]} },
	[138] = {nTaskType = 0, szShow = "Thu thËp C¸i bang c«n ph¸p", tbList = {allbrother_0801_tbItemList[137]} },
	--[139] = {nTaskType = 0, szShow = "Thu thËp V©n Long kÝch (M©u ph¸p)", tbList = {allbrother_0801_tbItemList[138]} },
	[140] = {nTaskType = 0, szShow = "Thu thËp L­u tinh (§ao ph¸p)", tbList = {allbrother_0801_tbItemList[139]} },
	[141] = {nTaskType = 0, szShow = "Thu thËp NhiÕp hån (Chó thuËt)", tbList = {allbrother_0801_tbItemList[140]} },
	[142] = {nTaskType = 0, szShow = "Thu thËp Th¸i cùc quyÒn phæ quyÓn 3", tbList = {allbrother_0801_tbItemList[141]} },
	[143] = {nTaskType = 0, szShow = "Thu thËp Th¸i cùc kiÕm phæ quyÓn 2", tbList = {allbrother_0801_tbItemList[142]} },
	[144] = {nTaskType = 0, szShow = "Thu thËp Ngù phong thuËt", tbList = {allbrother_0801_tbItemList[143]} },
	[145] = {nTaskType = 0, szShow = "Thu thËp Ngù l«i thuËt", tbList = {allbrother_0801_tbItemList[144]} },
	[146] = {nTaskType = 0, szShow = "Thu thËp Ngù t©m thuËt", tbList = {allbrother_0801_tbItemList[145]} },
	[147] = {nTaskType = 0, szShow = "Thu thËp LiÖt hång m·, D­¬ng chØ b¹ch ngäc (hÖ háa)", tbList = {allbrother_0801_tbItemList[146], allbrother_0801_tbItemList[180] }},
	[148] = {nTaskType = 0, szShow = "Thu thËp Hång m·, Lôc phØ thóy hé th©n phô (hÖ méc)", tbList = {allbrother_0801_tbItemList[147], allbrother_0801_tbItemList[181] }},
	[149] = {nTaskType = 0, szShow = "Thu thËp Hång li, Toµn th¹ch giíi chØ (hÖ kim)", tbList = {allbrother_0801_tbItemList[148], allbrother_0801_tbItemList[43] }},
	[150] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn h·n huyÕt m·, Toµn th¹ch giíi chØ (hÖ kim)", tbList = {allbrother_0801_tbItemList[149], allbrother_0801_tbItemList[43] }},
	[151] = {nTaskType = 0, szShow = "Thu thËp XÝch kÝ, D­¬ng chØ b¹ch ngäc (hÖ háa)", tbList = {allbrother_0801_tbItemList[150], allbrother_0801_tbItemList[180] }},
	[152] = {nTaskType = 0, szShow = "Thu thËp LiÖt h¾c m·, Phi phong", tbList = {allbrother_0801_tbItemList[151], allbrother_0801_tbItemList[183] }},
	[153] = {nTaskType = 0, szShow = "Thu thËp H¾c m·, D­¬ng chØ b¹ch ngäc (hÖ méc)", tbList = {allbrother_0801_tbItemList[152], allbrother_0801_tbItemList[184] }},
	[154] = {nTaskType = 0, szShow = "Thu thËp H¾c kú, B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[153], allbrother_0801_tbItemList[97] }},
	[155] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn h¾c m·, Lôc phØ thóy hé th©n phï (hÖ kim)", tbList = {allbrother_0801_tbItemList[154], allbrother_0801_tbItemList[44] }},
	[156] = {nTaskType = 0, szShow = "Thu thËp ¤ truy, Toµn th¹ch giíi chØ (hÖ méc)", tbList = {allbrother_0801_tbItemList[155], allbrother_0801_tbItemList[185] }},
	[157] = {nTaskType = 0, szShow = "Thu thËp LiÖt b¹ch m·, Toµn th¹ch h¹ng liªn (hÖ méc)", tbList = {allbrother_0801_tbItemList[156], allbrother_0801_tbItemList[186] }},
	[158] = {nTaskType = 0, szShow = "Thu thËp B¹ch m·, Long tiªn h­¬ng nang (hÖ thñy)", tbList = {allbrother_0801_tbItemList[157], allbrother_0801_tbItemList[187] }},
	[159] = {nTaskType = 0, szShow = "Thu thËp Ngäc hoa th«ng, Phi phong", tbList = {allbrother_0801_tbItemList[158], allbrother_0801_tbItemList[183] }},
	[160] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn b¹ch m·, D­¬ng chi b¹ch ngäc (hÖ kim)", tbList = {allbrother_0801_tbItemList[30], allbrother_0801_tbItemList[188] }},
	[161] = {nTaskType = 0, szShow = "Thu thËp Tóc s­¬ng, Lôc phØ thóy hé th©n phï (hÖ háa)", tbList = {allbrother_0801_tbItemList[5], allbrother_0801_tbItemList[189] }},
	[162] = {nTaskType = 0, szShow = "Thu thËp LiÖt hoµn m·, Toµn th¹ch giíi chØ (hÖ thñy)", tbList = {allbrother_0801_tbItemList[159], allbrother_0801_tbItemList[2] }},
	[163] = {nTaskType = 0, szShow = "Thu thËp Hoµng m·, Toµn th¹ch h¹ng liªn (hÖ thñy)", tbList = {allbrother_0801_tbItemList[160], allbrother_0801_tbItemList[46] }},
	[164] = {nTaskType = 0, szShow = "Thu thËp Hoµng phiªu, Long tiªn h­¬ng nang (hÖ méc)", tbList = {allbrother_0801_tbItemList[162], allbrother_0801_tbItemList[1] }},
	[165] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn hoµng m·, D­¬ng chi b¹ch ngäc (hÖ thæ)", tbList = {allbrother_0801_tbItemList[161], allbrother_0801_tbItemList[191] }},
	[166] = {nTaskType = 0, szShow = "Thu thËp Phi hoµng, Phi phong", tbList = {allbrother_0801_tbItemList[163], allbrother_0801_tbItemList[183] }},
	[167] = {nTaskType = 0, szShow = "Thu thËp LiÖt thanh m·, Toµn th¹ch giíi chØ (hÖ háa)", tbList = {allbrother_0801_tbItemList[164], allbrother_0801_tbItemList[192] }},
	[168] = {nTaskType = 0, szShow = "Thu thËp Thanh th«ng, Phi phong", tbList = {allbrother_0801_tbItemList[165], allbrother_0801_tbItemList[183] }},
	[169] = {nTaskType = 0, szShow = "Thu thËp Tö l­u, B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[166], allbrother_0801_tbItemList[97] }},
	[170] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn thanh m·, Toµn th¹ch h¹ng liªn (hÖ kim)", tbList = {allbrother_0801_tbItemList[167], allbrother_0801_tbItemList[193] }},
	[171] = {nTaskType = 0, szShow = "Thu thËp Ph¸ thiªn kÝch (hÖ thñy), Phi phong", tbList = {allbrother_0801_tbItemList[169], allbrother_0801_tbItemList[183] }},
	[172] = {nTaskType = 0, szShow = "Thu thËp HuyÒn thiÕt kiÕm (hÖ thæ), D­¬ng chi b¹ch ngäc (hÖ thñy)", tbList = {allbrother_0801_tbItemList[34], allbrother_0801_tbItemList[19] }},
	[173] = {nTaskType = 0, szShow = "Thu thËp Kim c« bæng (hÖ kim), B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[171], allbrother_0801_tbItemList[97] }},
	[174] = {nTaskType = 0, szShow = "Thu thËp Th«n nhËt tr¶m (hÖ thñy), Long tiªn h­¬ng nang (hÖ háa)", tbList = {allbrother_0801_tbItemList[172], allbrother_0801_tbItemList[194] }},
	[175] = {nTaskType = 0, szShow = "Thu thËp §¹i phong ®ao (hÖ háa), Toµn th¹ch giíi chØ (hÖ thæ)", tbList = {allbrother_0801_tbItemList[173], allbrother_0801_tbItemList[195] }},
	[176] = {nTaskType = 0, szShow = "Thu thËp Ph¸ thiªn chïy (hÖ kim), Toµn th¹ch h¹ng liªn (hÖ háa)", tbList = {allbrother_0801_tbItemList[48], allbrother_0801_tbItemList[196] }},
	[177] = {nTaskType = 0, szShow = "Thu thËp Ng­ l¹p (hÖ kim), B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[23], allbrother_0801_tbItemList[97] }},
	[178] = {nTaskType = 0, szShow = "Thu thËp To¸n ®Çu chïy (hÖ kim), Lôc phØ thóy hé th©n phï (hÖ thñy)", tbList = {allbrother_0801_tbItemList[176], allbrother_0801_tbItemList[190] }},
	[179] = {nTaskType = 0, szShow = "Thu thËp Tr­êng th­¬ng (hÖ thñy), Phi phong", tbList = {allbrother_0801_tbItemList[177], allbrother_0801_tbItemList[183] }},
	[180] = {nTaskType = 0, szShow = "Thu thËp NguyÖt nha thÝch (hÖ thñy), B¸ch qu¶ lé", tbList = {allbrother_0801_tbItemList[178], allbrother_0801_tbItemList[97] }},
	[181] = {nTaskType = 0, szShow = "Thu thËp T­îng b× hé uyÓn (hÖ kim), Lôc phØ thóy hé th©n phï (hÖ thæ)", tbList = {allbrother_0801_tbItemList[179], allbrother_0801_tbItemList[175] }},
	[182] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m ¤ng chñ Hµ"},
	[183] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m Qu¸ch viªn ngo¹i"},
	[184] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m Phan NhÞ Xu©n"},
	[185] = {nTaskType = 1, szShow = "§Õn Thµnh §« t×m T©n NhÞ ThÈm"},
	[186] = {nTaskType = 1, szShow = "§Õn Thµnh §« t×m Tèng cö nh©n"},
	[187] = {nTaskType = 1, szShow = "§Õn §¹i Lý t×m §ao Liªn Anh"},
	[188] = {nTaskType = 1, szShow = "§Õn Ph­îng T­êng t×m Tiªu côc"},
	[189] = {nTaskType = 1, szShow = "§Õn Ph­îng T­êng t×m Chu §å Phu"},
	[190] = {nTaskType = 1, szShow = "§Õn BiÖn Kinh t×m §¹i §é ThiÒn S­"},
	[191] = {nTaskType = 1, szShow = "§Õn BiÖn Kinh t×m Anh Tö"},
	[192] = {nTaskType = 1, szShow = "§Õn L©m An t×m T¹ ®¹i gia"},
	[193] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m TriÖu ®µ chñ"},
	[194] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m Giang NhÊt Tiªu"},
	[195] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m «ng chñ §ç"},
	[196] = {nTaskType = 1, szShow = "§Õn Giang T©n th«n t×m Qu¸ch Dòng"},
	[197] = {nTaskType = 1, szShow = "§Õn Th¹ch Cæ trÊn t×m ThÈm gia"},
	[198] = {nTaskType = 1, szShow = "§Õn VÜnh L¹c trÊn t×m bµ Th­"},
	[199] = {nTaskType = 1, szShow = "H·y ®Õn Long M«n trÊn t×m T«n NhÞ Lang!"},
	[200] = {nTaskType = 1, szShow = "§Õn Ba L¨ng HuyÖn Ph­¬ng Kh¶ VÞ"},
	[201] = {nTaskType = 1, szShow = "§Õn Nam Nh¹c TrÊn t×m §iÒn bµ bµ"},
	[202] = {nTaskType = 1, szShow = "§Õn Chu Tiªn TrÊn chñ l÷ qu¸n"},
	[203] = {nTaskType = 1, szShow = "§Õn Long TuyÒn Th«n t×m T« Hång Tô"},
	[204] = {nTaskType = 1, szShow = "§Õn §¹o H­¬ng Th«n t×m chñ tiÖm trµ"},
	[205] = {nTaskType = 1, szShow = "§Õn Thiªn V­¬ng bang t×m Ng­ Phô Hµ TÈu"},
	[206] = {nTaskType = 1, szShow = "§Õn ThiÕu l©m ph¸i La H¸n §­êng t×m HuyÒn Nan"},
	[207] = {nTaskType = 1, szShow = "§Õn Nga My ph¸i t×m DiÖu Èn t­íng c«ng"},
	[208] = {nTaskType = 1, szShow = "§Õn Nga My ph¸i t×m DiÖu KhiÕt"},
	[209] = {nTaskType = 1, szShow = "§Õn C¸i bang t×m Tõ Tam Tr­îng"},
	[210] = {nTaskType = 1, szShow = "§Õn Thiªn NhÉn gi¸o tÇng 3 t×m Qu©n s­"},
}
--¸öÈËÍê³ÉÈÎÎñ
function allbrother_0801_CompleteTask()
	local nTaskState	= GetTask(TSK_allbrother_0801_TaskState)
	local nTaskTime		= GetTask(TSK_allbrother_0801_TaskTime)
	
	if nTaskTime + TSKV_allbrother_0801_TaskTime <= GetCurServerTime() then --³¬Ê±
		SetTask(TSK_allbrother_0801_TaskState, 0)
		Msg2Player("Thêi gian hoµn thµnh nhiÖm vô ®· hÕt, nhiÖm vô thÊt b¹i!")
		return 0
	else
		nTaskState = nTaskState + 1073741824 --Ïàµ±ÓÚ×î¸ßÎ»ÉèÖÃÎª1
		SetTask(TSK_allbrother_0801_TaskState, nTaskState)
		Msg2Player("Hoµn thµnh nhiÖm vô B¾c §Èu L·o Nh©n giao cho.")
		return 1;
	end
	
end