-- 	tbMapLimit={
-- 	{nMapID = 19, nMapLevel = 30, szMapName = "KiÕm C¸c T©y Nam"},
-- 	{nMapID = 7, nMapLevel = 30, szMapName = "TÇng l¨ng tÇng 1"},
-- 	{nMapID = 21, nMapLevel = 40, szMapName = "Thanh Thµnh S¬n"},
-- 	{nMapID = 167, nMapLevel = 40, szMapName = "§iÓm Th­¬ng S¬n"},
-- 	{nMapID = 182, nMapLevel = 50, szMapName = "NghiÖt Long §éng"},
-- 	{nMapID = 164, nMapLevel = 50, szMapName = "Thiªn TÇm Th¸p"},
-- 	{nMapID = 79, nMapLevel = 60, szMapName = "T­¬ng D­¬ng Nha M«n MËt §¹o"},
-- 	{nMapID = 166, nMapLevel = 60, szMapName = "Thiªn TÇm Th¸p TÇng 3"},
-- 	{nMapID = 319, nMapLevel = 70, szMapName = "L©m Du Quan"},
-- 	{nMapID = 123, nMapLevel = 70, szMapName = "L·o Hæ §éng"},
-- 	{nMapID = 206, nMapLevel = 70, szMapName = "TÇng L¨ng TÇng 2"},
-- 	{nMapID = 224, nMapLevel = 80, szMapName = "Sa M¹c §Þa BiÓu"},
-- 	{nMapID = 198, nMapLevel = 80, szMapName = "Thanh Khª §éng"},
-- 	{nMapID = 320, nMapLevel = 80, szMapName = "Ch©n Nói Tr­êng B¹ch"},
-- 	{nMapID = 181, nMapLevel = 80, szMapName = "L­ìng Thñy §éng"},
-- 	{nMapID = 201, nMapLevel = 80, szMapName = "B¨ng Hµ §éng"},
-- 	{nMapID = 322, nMapLevel = 90, szMapName = "Tr­êng B¹ch S¬n B¾c"},
-- 	{nMapID = 321, nMapLevel = 90, szMapName = "Tr­êng B¹ch S¬n Nam"},
-- 	{nMapID = 75, nMapLevel = 90, szMapName = "Kháa Lang §éng"},
-- 	{nMapID = 225, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (1)"},
-- 	{nMapID = 226, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (2)"},
-- 	{nMapID = 227, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (3)"},
-- 	{nMapID = 336, nMapLevel = 90, szMapName = "Phong L¨ng §é"},
-- 	{nMapID = 340, nMapLevel = 90, szMapName = "M¹c Cao QuËt"},
-- 	{nMapID = 144, nMapLevel = 90, szMapName = "D­îc V­¬ng §éng(4)"},
-- 	{nMapID = 93, nMapLevel = 90, szMapName = "TiÕn Cóc §éng(mËt cung)"},
-- 	{nMapID = 124, nMapLevel = 90, szMapName = "C¸n Viªn §éng Mª Cung"},
-- 	{nMapID = 152, nMapLevel = 90, szMapName = "TuyÕt B¸o §éng TÇng 8"},
-- 	{nMapID = 949, nMapLevel = 90, szMapName = "Mª Cung KiÕm Gia"},

-- }


	tbMapLimit={
	{nMapID = 19, nMapLevel = 20, szMapName = "KiÕm C¸c T©y Nam"},
	{nMapID = 7, nMapLevel = 20, szMapName = "TÇng l¨ng tÇng 1"},
	{nMapID = 4, nMapLevel = 30, szMapName = "Kim Quan §éng"},
	{nMapID = 8, nMapLevel = 30, szMapName = "TÇng L¨ng Thñy Hoµng"},
	{nMapID = 22, nMapLevel = 30, szMapName = "B¹ch V©n §éng"},
	{nMapID = 74, nMapLevel = 30, szMapName = "Miªu LÜnh"},
	{nMapID = 77, nMapLevel = 30, szMapName = "YÕn Tö §éng"},
	{nMapID = 90, nMapLevel = 30, szMapName = "Phôc Ng­u S¬n §éng"},
	{nMapID = 92, nMapLevel = 30, szMapName = "Thôc C­¬ng S¬n"},
	{nMapID =136 , nMapLevel = 30, szMapName = "Kho¸i Ho¹t L©m"},
	{nMapID =141 , nMapLevel = 30, szMapName = "D­îc V­¬ng §éng(1)"},
	{nMapID = 145, nMapLevel = 30, szMapName = "TuyÕt B¸o §éng(1)"},
	{nMapID =146 , nMapLevel = 30, szMapName = "TuyÕt B¸o §éng (2)"},
	{nMapID =170 , nMapLevel = 30, szMapName = "Thæ phØ ®éng"},
	{nMapID = 193, nMapLevel = 30, szMapName = "Vò Di S¬n"},
	------------------------end of list map level 30------------------------
	{nMapID = 5, nMapLevel = 40, szMapName = "Kim Hoµng §éng"},
	{nMapID = 6, nMapLevel = 40, szMapName = "Táa V©ng §ong6"},
	{nMapID = 21, nMapLevel = 40, szMapName = "Thanh Thµnh S¬n"},
	{nMapID =23 , nMapLevel = 40, szMapName = "ThÇn Tiªn §éng"},
	{nMapID =28 , nMapLevel = 40, szMapName = "Tróc t¬ ®éng(3)"},
	{nMapID =41 , nMapLevel = 40, szMapName = "Phôc ng­u s¬n t©y"},
	{nMapID =91 , nMapLevel = 40, szMapName = "Mª cung kª qu¸n ®éng"},
	{nMapID = 113, nMapLevel = 40, szMapName = "MËt ThÊt ThiÕu l©m"},
	{nMapID =122 , nMapLevel = 40, szMapName = "Hoµng hµ nguyªn ®Çu"},
	{nMapID = 135, nMapLevel = 40, szMapName = "KiÕn tinh phong s¬n ®éng"},
	{nMapID = 167, nMapLevel = 40, szMapName = "§iÓm Th­¬ng S¬n"},
	{nMapID =168 , nMapLevel = 40, szMapName = "Phông nh·n ®éng"},
	{nMapID = 171, nMapLevel = 40, szMapName = "§iÓm th­¬ng s¬n ®éng(1)"},
	{nMapID = 172, nMapLevel = 40, szMapName = "§iÓm th­¬ng s¬n ®éng (2)"},
	{nMapID =173 , nMapLevel = 40, szMapName = "§iÓm th­¬ng s¬n ®éng (3)"},
	{nMapID =180 , nMapLevel = 40, szMapName = "Long Cung §éng"},

	-----------------------end of list level 40-----------------------------------
	{nMapID = 12, nMapLevel = 50, szMapName = "®Þa ®¹o hËu viÖn"},
	{nMapID = 24, nMapLevel = 50, szMapName = "H­ëng thñy ®éng"},
	{nMapID = 38, nMapLevel = 50, szMapName = "thiÕt th¸p (1)"},
	{nMapID =39 , nMapLevel = 50, szMapName = "thiÕt thap (2)"},
	{nMapID = 40, nMapLevel = 50, szMapName = "thiÕt th¸p (3)"},
	{nMapID =42 , nMapLevel = 50, szMapName = "Thiªn t©m ®éng"},
	{nMapID =66 , nMapLevel = 50, szMapName = "§¸y ®éng ®×nh hå"},
	{nMapID = 67, nMapLevel = 50, szMapName = "§¸y ®éng ®×nh hå (2)"},
	{nMapID =116 , nMapLevel = 50, szMapName = "Tr­êng v©n ®éng(1)"},
	{nMapID =125 , nMapLevel = 50, szMapName = "L­u tiªn ®éng(1)"},
	{nMapID =132 , nMapLevel = 50, szMapName = "B¨ng huyÖt ®éng"},
	{nMapID =147 , nMapLevel = 50, szMapName = "TuyÕt b¸o ®éng (3)"},
	{nMapID = 163, nMapLevel = 50, szMapName = "¸c b¸ ®Þa ®¹o"},
	{nMapID = 164, nMapLevel = 50, szMapName = "Thiªn TÇm Th¸p"},
	{nMapID =165 , nMapLevel = 50, szMapName = "Thiªn TÇm th¸p (2)"},
	{nMapID = 178, nMapLevel = 50, szMapName = "S¬n ®éng ngù hoa viªn"},
	{nMapID = 182, nMapLevel = 50, szMapName = "NghiÖt Long §éng"},
	{nMapID =194 , nMapLevel = 50, szMapName = "Ngäc Hoa ®éng"},
--------------------------------------------end of list level 50-----------------
	{nMapID = 26, nMapLevel = 60, szMapName = "Tróc t¬ ®éng(1)"},
	{nMapID =51 , nMapLevel = 60, szMapName = "Th¸nh ®éng(1)"},
	{nMapID =52 , nMapLevel = 60, szMapName = "Th¸nh ®éng(2)"},
	{nMapID =56 , nMapLevel = 60, szMapName = "hoµnh s¬n ph¸i"},
	{nMapID =68 , nMapLevel = 60, szMapName = "thanh loa ®¶o"},
	{nMapID = 79, nMapLevel = 60, szMapName = "T­¬ng D­¬ng Nha M«n MËt §¹o"},
	{nMapID = 114, nMapLevel = 60, szMapName = "108 La h¸n trËn"},
	{nMapID =117 , nMapLevel = 60, szMapName = "T­êng v©n ®éng(2)"},
	{nMapID = 118, nMapLevel = 60, szMapName = "T­êng v©n ®éng (3)"},
	{nMapID = 119, nMapLevel = 60, szMapName = "T­êng V©n §éng (4)"},
	{nMapID = 126, nMapLevel = 60, szMapName = "L­u tiªn ®éng (2)"},
	{nMapID =127 , nMapLevel = 60, szMapName = "L­u tiªn ®éng (3)"},
	{nMapID = 128, nMapLevel = 60, szMapName = "l­u tiªn ®éng(4)"},
	{nMapID = 148, nMapLevel = 60, szMapName = "TuyÕt b¸o ®éng (4)"},
	{nMapID =158 , nMapLevel = 60, szMapName = "Mª cung cÊm ®Þa"},
	{nMapID = 166, nMapLevel = 60, szMapName = "Thiªn TÇm Th¸p TÇng 3"},
	{nMapID =196 , nMapLevel = 60, szMapName = "D­¬ng gi¸c ®éng"},
	-----------------------------------end of 60-----------------------------------------------------------
	{nMapID =9 , nMapLevel = 70, szMapName = "tr­êng giang nguyªn ®Çu"},
	{nMapID =27 , nMapLevel = 70, szMapName = "tróc to8 ®éng (2)"},
	{nMapID =55 , nMapLevel = 70, szMapName = "§µo hoa nguyªn"},
	{nMapID =69 , nMapLevel = 70, szMapName = "Thanh loa ®¶o d¬n ®éng"},
	{nMapID = 72, nMapLevel = 70, szMapName = "§¹i tï ®éng"},
	{nMapID =76  ,nMapLevel = 70, szMapName = "S¬n b¶o ®éng"},
	{nMapID = 94 ,nMapLevel = 70, szMapName = "linh cèc ®éng"},
	{nMapID = 120, nMapLevel = 70, szMapName = "t­êng v©n ®éng (5)"},
	{nMapID = 123, nMapLevel = 70, szMapName = "L·o Hæ §éng"},
	{nMapID =129 , nMapLevel = 70, szMapName = "L­u tiªn ®éng(5)"},
	{nMapID = 130, nMapLevel = 70, szMapName = "l­u tiªn ®éng (6)"},
	{nMapID = 142, nMapLevel = 70, szMapName = "D­îc v­¬ng ®éng(2)"},
	{nMapID = 149, nMapLevel = 70, szMapName = "TuyÕt b¸o ®éng(5)"},
	{nMapID = 169, nMapLevel = 70, szMapName = "Long Nh·n ®éng"},
	{nMapID = 206 ,nMapLevel = 70, szMapName = "TÇn l¨ng 2"},
	{nMapID = 319 ,nMapLevel = 70, szMapName = "L©m du quan"},
---------------------------------------------------end of 70------------------------------------
	{nMapID = 10 ,nMapLevel = 80, szMapName = "Nh¹n th¹ch ®éng"},
	{nMapID = 143 ,nMapLevel = 80, szMapName = "D­îc v­¬ng ®éng(3)"},
	{nMapID = 150 ,nMapLevel = 80, szMapName = "TuyÕt b¸o ®éng(6)"},
	{nMapID =151  ,nMapLevel = 80, szMapName = "TuyÕt b¸o ®éng(7)"},
	{nMapID = 181, nMapLevel = 80, szMapName = "L­ìng Thñy §éng"},
	{nMapID = 198, nMapLevel = 80, szMapName = "Thanh Khª §éng"},
	{nMapID = 199 ,nMapLevel = 80, szMapName = "Vò l¨ng ®éng"},
	{nMapID = 200 ,nMapLevel = 80, szMapName = "Cæ d­¬ng ®éng"},
	{nMapID =201  ,nMapLevel = 80, szMapName = "B¨ng hµ ®éng"},
	{nMapID = 202 ,nMapLevel = 80, szMapName = "Phï dung ®éng"},
	{nMapID = 203 ,nMapLevel = 80, szMapName = "V« danh ®éng"},
	{nMapID = 204 ,nMapLevel = 80, szMapName = "Phi thiªn ®éng"},
	{nMapID = 205 ,nMapLevel = 80, szMapName = "D­¬ng trung ®éng"},
	{nMapID = 207 ,nMapLevel = 80, szMapName = "tÇn l¨ng 3"},
	{nMapID = 224, nMapLevel = 80, szMapName = "Sa M¹c §Þa BiÓu"},
	{nMapID = 320, nMapLevel = 80, szMapName = "Ch©n Nói Tr­êng B¹ch"},
	--------------------------------------end of 90--------------------------------------------------------
	{nMapID = 75, nMapLevel = 90, szMapName = "Kháa Lang §éng"},
	{nMapID = 93, nMapLevel = 90, szMapName = "TiÕn Cóc §éng(mËt cung)"},
	{nMapID = 124, nMapLevel = 90, szMapName = "C¸n Viªn §éng Mª Cung"},
	{nMapID = 144, nMapLevel = 90, szMapName = "D­îc V­¬ng §éng(4)"},
	{nMapID = 152, nMapLevel = 90, szMapName = "TuyÕt B¸o §éng TÇng 8"},
	{nMapID = 225, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (1)"},
	{nMapID = 226, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (2)"},
	{nMapID = 227, nMapLevel = 90, szMapName = "Sa M¹c Mª Cung (3)"},
	{nMapID = 321, nMapLevel = 90, szMapName = "Tr­êng B¹ch S¬n Nam"},
	{nMapID = 322, nMapLevel = 90, szMapName = "Tr­êng B¹ch S¬n B¾c"},
	{nMapID = 340, nMapLevel = 90, szMapName = "M¹c Cao QuËt"},
	{nMapID = 341 ,nMapLevel = 90, szMapName = "M¹c b¾c th¶o nguyªn"},
	{nMapID =342  ,nMapLevel = 90, szMapName = "Vi s¬n ®¶o"},
	{nMapID = 875 ,nMapLevel = 90, szMapName = "H¾c sa ®éng"},
	{nMapID = 336, nMapLevel = 90, szMapName = "Phong L¨ng §é"},
	{nMapID = 949, nMapLevel = 90, szMapName = "Mª Cung KiÕm Gia"},

}


--NewWorld(53, 1626, 3179)--phï ba l¨ng huyÖn